/**
 * previewData.mjs — ONE reader for the offline preview data (WO-09 R2 Part C).
 *
 * The single `movementPreviewManifest.json` is replaced by an index
 * (`previewIndex.json`: the shared rig, box, character and frame interval, plus
 * movement id -> family) and one compact file per motion family
 * (`families/<family>.json`). Both are generated by
 * tools/rendering/wo09_split_preview_manifest.mjs.
 *
 * Every offline tool and the e2e suite read through THIS module, so the split
 * has exactly one reader to keep honest: `loadPreviewManifest()` returns the
 * same shape the tools were written against, with entry values identical to the
 * file it replaced.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = path.resolve(__dirname, '..', '..', '..');
const PREVIEW_DIR = path.join(PROJECT_ROOT, 'apps', 'mobile', 'src', 'components', 'movementPreview');
export const INDEX_PATH = path.join(PREVIEW_DIR, 'previewIndex.json');
export const FAMILIES_DIR = path.join(PREVIEW_DIR, 'families');

/** The family files, in a stable order. */
export function familyFilePaths() {
  return fs
    .readdirSync(FAMILIES_DIR)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => path.join(FAMILIES_DIR, name));
}

/** Every preview data file: the index first, then the family files. */
export function previewDataPaths() {
  return [INDEX_PATH, ...familyFilePaths()];
}

/** The raw text of every preview data file, as [path, text] pairs. */
export function readPreviewDataSources() {
  return previewDataPaths().map((file) => [file, fs.readFileSync(file, 'utf8')]);
}

/** The parsed index. */
export function loadPreviewIndex() {
  return JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
}

/**
 * The digest of the preview data a render was made from: every preview data
 * file, in `previewDataPaths()` order, each contributed as its file name, a NUL
 * and its bytes (so a file boundary can never be forged by concatenation).
 *
 * Before R2 Part C this was `sha256` of the single manifest file; the evidence
 * index keeps that field name, and the value now covers the split.
 */
export function previewDataDigest() {
  const hash = createHash('sha256');
  for (const file of previewDataPaths()) {
    hash.update(path.basename(file));
    hash.update('\0');
    hash.update(fs.readFileSync(file));
    hash.update('\0');
  }
  return hash.digest('hex');
}

/**
 * The merged manifest shape the offline tools were written against: the
 * index's shared blocks plus every family's entries, in the manifest's own
 * order. Values are identical to the single file the split replaced.
 */
// One definition for the split generator and tier-1 checks. Storage limits count
// UTF-8 file bytes (including the final newline); gzip covers index + sorted
// family files concatenated once. These are engineering guards, not device RAM.
export const PREVIEW_BUDGETS = {
  // Full300 scope supersedes the bounded prototype aggregate, retaining
  // family/lazy-load/heap guards. See movement-completion/ASSET_BUDGET_DECISION.md.
  rawBytes: 1048576,
  gzipBytes: 196608,
  // Retained at 64 KiB by delegated R4 decision, 2026-09-30. Supersedes the
  // historical 24 KiB guide under queue ruling 6 / ledger Entries 0176-0177.
  // The full300 aggregate decision does not raise this family or heap limit.
  familyBytes: 65536,
  // Node JSON-clone regression thresholds only: not native/peak memory bounds.
  singleFamilyMaxBytes: 262144,
  allFamiliesMaxBytes: 2097152,
};

export function loadPreviewManifest() {
  const index = loadPreviewIndex();
  const byMovementId = new Map();
  for (const file of familyFilePaths()) {
    const family = JSON.parse(fs.readFileSync(file, 'utf8'));
    for (const entry of family.entries) {
      if (byMovementId.has(entry.movementId)) {
        throw new Error(`preview data: entry ${entry.movementId} appears in more than one family file`);
      }
      byMovementId.set(entry.movementId, entry);
    }
  }
  if (byMovementId.size !== index.movementOrder.length) {
    throw new Error(
      `preview data: the index orders ${index.movementOrder.length} entries but the family files carry ${byMovementId.size}`);
  }
  return {
    schemaVersion: index.schemaVersion,
    scope: index.scope,
    techniqueReview: index.techniqueReview,
    sharedRig: index.sharedRig,
    box: index.box,
    character: index.character,
    frameIntervalMs: index.frameIntervalMs,
    entries: index.movementOrder.map((movementId) => {
      const entry = byMovementId.get(movementId);
      if (entry === undefined) {
        throw new Error(`preview data: entry ${movementId} is missing from its family`);
      }
      return entry;
    }),
  };
}
