// What each chain movement shows and says: the phase at each keyframe (0 is
// the movement's first pose in CHAIN_MOVEMENTS, 1 its second, and so on), how
// long each gap takes, and the caption under each keyframe. Captions and
// timings come from the movement's own catalogue text. Every gap is eased in
// and out, so a continuous movement is ONE gap: a keyframe half-way up would
// make the limb hesitate there.
export const CHAIN_SPECS = [
  {
    id: 219,
    slug: 'incline-dumbbell-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower slowly until the arms are straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms hanging straight down and palms facing forward.',
      'Keeping the upper arms still, curl the dumbbells up to shoulder height.',
      'Pause at the top.',
      'Lower slowly until the arms are straight.',
      'Back stays on the bench. Lower to a full stretch.',
    ],
    reason: 'Source-bound side-view draft. Sitting back on an incline bench with the back and head on the pad; the upper arms hang straight down and do not move while the forearms curl the dumbbells to shoulder height, pause, and lower more slowly to straight arms. The palms-forward grip is shown by the bells reading end-on. Not drawn: the bench angle is not given by the source, so 60 degrees is a drawing choice.',
    summary: 'Sitting back on an incline bench, curl the dumbbells to shoulder height with the upper arms hanging still, pause, then lower slowly to straight arms.',
  },
  {
    id: 221,
    slug: 'incline-hammer-curls',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Pause at the top, then lower slowly until the arms are straight."
    segments: [1300, 700, 2000, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms hanging straight down and palms facing each other.',
      'Keeping the upper arms still and the palms facing in, bend the elbows to curl the dumbbells up.',
      'Pause at the top.',
      'Lower slowly until the arms are straight.',
      'Palms face each other throughout. Upper arms hang still.',
    ],
    reason: 'Source-bound side-view draft. Sitting back on an incline bench; the upper arms hang straight down and stay still while the elbows bend, with the palms facing each other for the whole rep, so each dumbbell is seen along its length and stays square to the forearm. A pause at the top, then a slower lowering to straight arms. Not drawn: the bench angle is not given by the source, so 60 degrees is a drawing choice.',
    summary: 'Sitting back on an incline bench with palms facing in, curl the dumbbells up with the upper arms hanging still, pause, then lower slowly to straight arms.',
  },
  {
    id: 207,
    slug: 'front-incline-dumbbell-raise',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze for a second, then lower back to the start."
    segments: [1200, 1000, 1600, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms straight in front, palms down, dumbbells just above the thighs.',
      'Keeping the elbows locked, raise the dumbbells straight up until they are slightly above shoulder height.',
      'Squeeze for a second. Keep the head resting on the bench.',
      'Lower back to the start.',
      'Keep the elbows locked straight.',
    ],
    reason: 'Source-bound side-view draft. Reclined on a bench set at 45 degrees, inside the 30 to 60 degrees the source allows, with the head resting on the pad; the arms stay locked straight and lift the dumbbells from just above the thighs to slightly above shoulder height, hold for one second, and lower. The palms-down grip is shown by the bells reading end-on.',
    summary: 'Reclined on an incline bench, raise the dumbbells with locked arms from just above the thighs to slightly above shoulder height, squeeze for a second, then lower.',
  },
  {
    id: 155,
    slug: 'cable-incline-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then let the bar return slowly until the elbows are bent again."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Lie back on an incline bench facing away from a high pulley and take the bar overhead with a narrow overhand grip, elbows tucked in and bent.',
      'Keeping the upper arms still, straighten the elbows until the arms are fully extended.',
      'Pause and squeeze the triceps.',
      'Let the bar return slowly until the elbows are bent again.',
      'Upper arms stay still. Squeeze the triceps at full extension.',
    ],
    reason: 'Source-bound side-view draft. Lying back on an incline bench facing away from a high pulley; the upper arms stay fixed beside the head while the elbows straighten from a right angle to fully extended, pause, and bend again more slowly. The pulley is placed where the forearms point at the start, so the cable only lengthens as the arms extend. Not drawn: the narrow overhand grip, which a side view cannot show; the bar reads end-on at the hands.',
    summary: 'Lying back on an incline bench facing away from a high pulley, straighten the elbows with the upper arms fixed beside the head, pause, then let the bar return slowly.',
  },
  {
    id: 179,
    slug: 'decline-dumbbell-triceps-extension',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly beside the ears."
    segments: [1700, 250, 1100, 500],
    captions: [
      'Secure the legs on a decline bench, lie back and hold a dumbbell in each hand above the chest, palms facing each other and arms straight.',
      'Keeping the upper arms still and the elbows in, bend the elbows to lower the dumbbells beside the ears.',
      'Upper arms stay still. Elbows point at the ceiling.',
      'Straighten the elbows to return the dumbbells above the chest.',
      'Arms straight above the chest again.',
    ],
    reason: 'Source-bound side-view draft. Lying back on a decline bench, head at the low end, knees over the high end and ankles hooked under a roller; the upper arms point up from the lying chest, 15 degrees back from plumb, and do not move while the elbows bend to bring the dumbbells down beside the ears, slowly, and straighten again. The palms-in grip is shown by each bell being seen along its length, square to the forearm. Not drawn: the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Lying back on a decline bench with the legs secured, lower the dumbbells beside the ears by bending only the elbows, then straighten the arms above the chest.',
  },
  {
    id: 180,
    slug: 'decline-ez-bar-triceps-extension',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly toward the forehead."
    segments: [1600, 250, 1000, 500],
    captions: [
      'Secure the legs on a decline bench, lie back and hold the EZ bar above the chest with a grip slightly narrower than shoulder width, arms straight.',
      'Keeping the upper arms still, bend the elbows to lower the bar toward the forehead.',
      'Upper arms stay still, elbows in, bar just above the forehead.',
      'Straighten the elbows to return the bar above the chest.',
      'Arms straight above the chest again.',
    ],
    reason: 'Source-bound side-view draft. Lying back on a decline bench with the legs secured under a roller; the upper arms point up from the lying chest, 15 degrees back from plumb, and stay still while the elbows bend to lower the EZ bar toward the forehead, slowly, stopping just above it, and straighten again. The bar is one implement through both hands and reads end-on with its cambered shaft. Not drawn: the grip width, which a side view cannot show; the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Lying back on a decline bench with the legs secured, lower the EZ bar toward the forehead by bending only the elbows, then straighten the arms above the chest.',
  },
  {
    id: 156,
    slug: 'cable-lying-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly to the forehead line." ... "return the bar above the chest and pause."
    segments: [1600, 250, 1000, 700],
    captions: [
      'Lie on a flat bench with your head toward a low pulley and hold the bar with a narrow overhand grip, arms straight above the chest.',
      'Keeping the upper arms still and the elbows in, bend the elbows to lower the bar until it is just above the forehead.',
      'Elbows in, upper arms pointing at the ceiling.',
      'Straighten the elbows to return the bar above the chest.',
      'Pause with the arms straight above the chest.',
    ],
    reason: 'Source-bound side-view draft. Lying on a flat bench with the head toward a low pulley, feet on the floor; the upper arms point at the ceiling and stay there while the elbows bend to lower the bar to just above the forehead, then straighten, with a pause at the top. The cable runs from the pulley past the end of the bench to the bar without crossing the bench or the head, and only lengthens as the arms straighten. Not drawn: the narrow overhand grip, which a side view cannot show.',
    summary: 'Lying on a flat bench with the head toward a low pulley, lower the bar to just above the forehead by bending only the elbows, then straighten the arms and pause.',
  },
  {
    id: 237,
    slug: 'low-cable-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then let the elbows bend slowly back to a right angle."
    segments: [1100, 600, 1900, 500],
    captions: [
      'Lie face up on the bench of a seated row station, head toward the pulley, holding the rope ends with palms facing each other, upper arms pointing at the ceiling and elbows bent to a right angle.',
      'Keeping the upper arms still, straighten the elbows until the forearms are vertical.',
      'Squeeze with the forearms vertical.',
      'Let the elbows bend slowly back to a right angle.',
      'Upper arms point at the ceiling. Only the forearms move.',
    ],
    reason: 'Source-bound side-view draft. Face up on the low bench of a seated row station with the head toward the low pulley and a rope in the hands; the upper arms point at the ceiling and stay there while the forearms go from level, elbows at a right angle, to vertical, hold, and return slowly to a right angle and no further. The cable only lengthens as the arms straighten. Not drawn: the palms-in grip on the rope ends, which a side view cannot show.',
    summary: 'Face up on a row-station bench with the head toward the low pulley, straighten the elbows until the forearms are vertical, squeeze, then let them bend slowly back to a right angle.',
  },
  {
    id: 276,
    slug: 'spider-curl',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then lower slowly until the arms are straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Lie with the chest and stomach against the angled side of a preacher bench, feet on the floor, upper arms resting on the pad, arms straight.',
      'Keeping the upper arms on the pad, curl the bar up as far as you can.',
      'Squeeze at the top.',
      'Lower slowly until the arms are straight.',
      'Chest stays on the bench. Upper arms stay on the pad.',
    ],
    reason: 'Source-bound side-view draft. The source sets this up its own way, so the drawing follows it and not the usual hanging-arm spider curl: chest and stomach lie against the angled side of a preacher pad, feet on the floor, and the upper arms lie down the pad\'s other side with their backs resting on it. That far side is drawn sloping, square to the angled side: in this rig a plumb face cannot reach a hanging upper arm, so only the lower part of each upper arm is on the pad. They stay there while the bar is curled from straight arms as far as it goes, held, and lowered slowly to straight arms. Not drawn: the shoulder-width underhand grip, which a side view cannot show; the bar reads end-on at the hands.',
    summary: 'Chest and stomach against the angled side of a preacher bench, upper arms on the pad: curl the bar up as far as you can, squeeze, then lower slowly to straight arms.',
  },
  {
    id: 171,
    slug: 'concentration-curls',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then lower slowly until the arm is straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit on a flat bench with the feet wide, hold one dumbbell and rest the back of that upper arm against the inner thigh, arm straight, palm facing forward.',
      'Keeping the upper arm still, curl the dumbbell up toward the shoulder.',
      'Squeeze at the top.',
      'Lower slowly until the arm is straight.',
      'Complete the repetitions, then change arms.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model seen nearly from the front, turned 72 degrees, so the wide feet and the inner thigh both show. Seated on a flat bench, leaning forward, the back of the working upper arm rests against the inner thigh and stays there while the forearm curls the dumbbell from a straight arm up toward the shoulder, holds, and lowers slowly. The free hand rests on the other knee; the source does not say where it goes. One side is shown; the last caption carries the change of arms.',
    summary: 'Seated with the feet wide and the back of the upper arm against the inner thigh, curl one dumbbell up toward the shoulder, squeeze, lower slowly to a straight arm, then change arms.',
  },
  {
    id: 268,
    slug: 'seated-dumbbell-palms-down-wrist-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly"
    segments: [1000, 300, 1700, 500],
    captions: [
      'Sit on the edge of a flat bench with the forearms resting on the thighs, palms facing down, wrists just past the knees. Let the wrists drop.',
      'Lift the backs of the hands as far as the range allows without the elbows moving.',
      'Keep the forearms flat and still.',
      'Lower slowly.',
      'When the elbows lift to help, reduce the load.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on the edge of a flat bench, leaning forward with the forearms level along the thighs and the wrists just past the knees; only the hands move, from dropped to lifted and slowly back, with the dumbbells held under the knuckles because the palms face down. Not drawn: a close-up of the hand. The catalogue asks for one, and this frame shows the whole seated figure, so the wrist movement is small on screen.',
    summary: 'Forearms flat on the thighs, palms down: let the wrists drop, lift the backs of the hands as far as they go without moving the elbows, then lower slowly.',
  },
  {
    id: 269,
    slug: 'seated-dumbbell-palms-up-wrist-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly into the stretch"
    segments: [1000, 300, 1700, 500],
    captions: [
      'Sit on the edge of a flat bench with the forearms resting on the thighs, palms facing up, wrists just past the knees. Let the wrists open under the load.',
      'Curl the palms up as far as the range allows without the elbows moving.',
      'Keep the forearms flat and still.',
      'Lower slowly into the stretch.',
      'When the elbows lift to help, reduce the load.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on the edge of a flat bench, leaning forward with the forearms level along the thighs and the wrists just past the knees; only the hands move, from open under the load to curled up and slowly back, with the dumbbells resting on top of the hands because the palms face up. Not drawn: a close-up of the hand. The catalogue asks for one, and this frame shows the whole seated figure, so the wrist movement is small on screen.',
    summary: 'Forearms flat on the thighs, palms up: let the wrists open, curl the palms up as far as they go without moving the elbows, then lower slowly into the stretch.',
  },
  {
    id: 164,
    slug: 'cable-wrist-curl',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower the bar slowly until the wrists are extended again."
    segments: [1000, 600, 1700, 500],
    captions: [
      'Sit on a bench facing a low pulley, grip the bar palms-up and rest the forearms on the thighs with the wrists just past the knees.',
      'Keeping the forearms still, curl the wrists up as far as they go.',
      'Pause at the top.',
      'Lower the bar slowly until the wrists are extended again.',
      'Forearms stay on the thighs. Only the wrists move.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on a bench facing a low pulley, forearms level along the thighs and the wrists just past the knees; only the hands move, curling the bar up from extended wrists, pausing, and lowering slowly. The pulley sits below the line of the dropped hands, so the cable only lengthens as the wrists curl. Not drawn: the shoulder-width grip, which a side view cannot show, and a close-up of the hand, which the catalogue asks for; this frame shows the whole seated figure.',
    summary: 'Seated facing a low pulley with the forearms on the thighs, curl the wrists up as far as they go, pause, then lower the bar slowly until the wrists are extended again.',
  },
  {
    id: 95,
    slug: 'sit-up',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "Roll down as slowly as you rose."
    segments: [1900, 300, 1900, 500],
    captions: [
      'Lie on your back with knees bent, feet flat, hands crossed on your chest.',
      'Curl your torso up one segment at a time until your chest meets your thighs.',
      'Exhale on the way up.',
      'Roll back down the same way, as slowly as you rose.',
      'Peel up one vertebra at a time.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Knees bent, feet flat, hands crossed on the chest; the trunk peels off the floor from the head end while the lower back is still down, then the whole curled trunk comes up until the chest meets the thighs, and it rolls back down the same way in the same time. The trunk is drawn along the curled spine, not as one stiff piece pivoting at the hips, which the source calls a different movement.',
    summary: 'Knees bent and feet flat, curl the torso up one segment at a time until the chest meets the thighs, then roll back down the same way.',
  },
  {
    id: 124,
    slug: 'tuck-crunch',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "Pause with the abdominals shortened, then lower both ends slowly."
    segments: [1100, 600, 1800, 500],
    captions: [
      'Lie on your back with the hips and knees bent and the arms reaching toward the feet.',
      'Bring the ribs and pelvis toward one another, curling the shoulders up as the knees travel slightly toward the chest.',
      'Pause with the abdominals shortened. Reach past the hips.',
      'Lower both ends slowly.',
      'Lower both ends on the same slow count.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Hips and knees bent with the shins level, arms reaching toward the feet; the upper spine curls so the shoulders come up while the knees travel a little toward the chest, a pause, then both ends lower slowly together. Not drawn: the pelvis tilting toward the ribs. The lower back stays on the floor in this drawing and the knees carry that half of the movement.',
    summary: 'Hips and knees bent, arms reaching toward the feet: curl the shoulders up as the knees travel slightly toward the chest, pause, then lower both ends slowly.',
  },
  {
    id: 72,
    slug: 'reverse-crunch',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "Lower the hips slow"
    segments: [1100, 250, 1900, 500],
    captions: [
      'Lie on your back with knees bent over your hips, hands flat beside you.',
      'Curl your hips off the floor, bringing the knees towards your ribs: the pelvis rolls up, the legs do not swing.',
      'Roll the pelvis up towards the ribs.',
      'Lower the hips back down slowly.',
      'Keep the feet floating between reps.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Knees bent over the hips, hands flat beside the body, shoulders on the floor; the lower spine curls so the pelvis rolls up and the hips leave the floor, with the legs riding on the pelvis and keeping their shape, then the hips lower more slowly. The feet stay off the floor for the whole cycle.',
    summary: 'Knees bent over the hips, roll the pelvis up so the hips leave the floor and the knees come towards the ribs, then lower the hips slowly without the feet touching down.',
  },
  {
    id: 99,
    slug: 'cable-reverse-crunch',
    equipment: 'cable_machine',
    phases: [0, 2, 2, 0, 0],
    // "Set the hips down on a slow count."
    segments: [1300, 300, 2000, 500],
    captions: [
      'Attach both ankles to a low cable, lie facing away from the stack, hips and knees near 90 degrees, shoulders heavy on the floor.',
      'Tuck the pelvis first, then curl the knees toward the ribs until the tailbone lifts without throwing the legs.',
      'Curl the knees toward the ribs.',
      'Set the hips down slowly while keeping cable tension.',
      'Start with the pelvis tucked.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying with the head away from the stack and a low cable to the ankles, hips and knees at right angles, shoulders on the floor; the pelvis tucks first, then the lower spine curls so the tailbone lifts and the knees come toward the ribs, with the legs riding on the pelvis, and the hips set down more slowly. The cable stays taut and only lengthens as the knees come in. Not drawn: the ankle cuffs; the cable ends at the ankle.',
    summary: 'Lying with a low cable on the ankles, tuck the pelvis, curl the knees toward the ribs until the tailbone lifts, then set the hips down slowly with the cable still tight.',
  },
  {
    id: 150,
    slug: 'bent-knee-hip-raise',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "Squeeze at the top for a second, then lower slowly to the start."
    segments: [1500, 1000, 2100, 500],
    captions: [
      'Lie flat on the floor with the arms beside you, knees bent to about seventy-five degrees and the feet a couple of inches up.',
      'Draw the knees toward the chest, holding that knee angle, until the pelvis rolls back and the hips leave the floor.',
      'Squeeze at the top for a second.',
      'Lower slowly to the start.',
      'Hold the knee angle throughout.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying flat with the arms beside the body, knees bent 75 degrees and the feet just clear of the floor; the knees are drawn toward the chest at that same knee angle, then the lower spine curls so the pelvis rolls back and the hips leave the floor, a one-second hold, and a slower return to the start.',
    summary: 'Lying flat with the knees bent and the feet just off the floor, draw the knees toward the chest at the same knee angle until the hips leave the floor, squeeze for a second, then lower slowly.',
  },
  {
    id: 183,
    slug: 'decline-reverse-crunch',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "Pause, then lower the hips and return the legs slowly to the start."
    segments: [1500, 600, 2200, 500],
    captions: [
      'Lie on a decline bench with the head at the high end, hold the top of the bench and raise the legs, knees slightly bent, until they are level with the floor.',
      'Draw the knees toward the chest and roll the pelvis so the hips lift off the bench.',
      'Pause at the top. Hold the bench firmly.',
      'Lower the hips and return the legs slowly to the start.',
      'Legs level with the floor again, knees slightly bent.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying on a decline bench with the head at the high end and the hands holding the top of the bench; the legs start level with the floor with the knees slightly bent, the knees are drawn toward the chest, then the lower spine curls so the pelvis rolls and the hips lift off the bench, a pause, and a slower return. Not drawn: the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Head at the high end of a decline bench and hands on its top, draw the knees toward the chest and roll the pelvis so the hips lift off the bench, pause, then return slowly.',
  },
];
