// What each chain movement shows and says: the phase at each keyframe (0 is
// the movement's first pose in CHAIN_MOVEMENTS, 1 its second, and so on), how
// long each gap takes, and the caption under each keyframe. Captions and
// timings come from the movement's own catalogue text. Every gap is eased in
// and out, so a continuous movement is ONE gap: a keyframe half-way up would
// make the limb hesitate there.
export const CHAIN_SPECS = [
  {
    id: 219,
    slug: 'incline-dumbbell-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower slowly until the arms are straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms hanging straight down and palms facing forward.',
      'Keeping the upper arms still, curl the dumbbells up to shoulder height.',
      'Pause at the top.',
      'Lower slowly until the arms are straight.',
      'Back stays on the bench. Lower to a full stretch.',
    ],
    reason: 'Source-bound side-view draft. Sitting back on an incline bench with the back and head on the pad; the upper arms hang straight down and do not move while the forearms curl the dumbbells to shoulder height, pause, and lower more slowly to straight arms. The palms-forward grip is shown by the bells reading end-on. Not drawn: the bench angle is not given by the source, so 60 degrees is a drawing choice.',
    summary: 'Sitting back on an incline bench, curl the dumbbells to shoulder height with the upper arms hanging still, pause, then lower slowly to straight arms.',
  },
  {
    id: 221,
    slug: 'incline-hammer-curls',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Pause at the top, then lower slowly until the arms are straight."
    segments: [1300, 700, 2000, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms hanging straight down and palms facing each other.',
      'Keeping the upper arms still and the palms facing in, bend the elbows to curl the dumbbells up.',
      'Pause at the top.',
      'Lower slowly until the arms are straight.',
      'Palms face each other throughout. Upper arms hang still.',
    ],
    reason: 'Source-bound side-view draft. Sitting back on an incline bench; the upper arms hang straight down and stay still while the elbows bend, with the palms facing each other for the whole rep, so each dumbbell is seen along its length and stays square to the forearm. A pause at the top, then a slower lowering to straight arms. Not drawn: the bench angle is not given by the source, so 60 degrees is a drawing choice.',
    summary: 'Sitting back on an incline bench with palms facing in, curl the dumbbells up with the upper arms hanging still, pause, then lower slowly to straight arms.',
  },
  {
    id: 207,
    slug: 'front-incline-dumbbell-raise',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze for a second, then lower back to the start."
    segments: [1200, 1000, 1600, 500],
    captions: [
      'Sit back on an incline bench with a dumbbell in each hand, arms straight in front, palms down, dumbbells just above the thighs.',
      'Keeping the elbows locked, raise the dumbbells straight up until they are slightly above shoulder height.',
      'Squeeze for a second. Keep the head resting on the bench.',
      'Lower back to the start.',
      'Keep the elbows locked straight.',
    ],
    reason: 'Source-bound side-view draft. Reclined on a bench set at 45 degrees, inside the 30 to 60 degrees the source allows, with the head resting on the pad; the arms stay locked straight and lift the dumbbells from just above the thighs to slightly above shoulder height, hold for one second, and lower. The palms-down grip is shown by the bells reading end-on.',
    summary: 'Reclined on an incline bench, raise the dumbbells with locked arms from just above the thighs to slightly above shoulder height, squeeze for a second, then lower.',
  },
  {
    id: 155,
    slug: 'cable-incline-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then let the bar return slowly until the elbows are bent again."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Lie back on an incline bench facing away from a high pulley and take the bar overhead with a narrow overhand grip, elbows tucked in and bent.',
      'Keeping the upper arms still, straighten the elbows until the arms are fully extended.',
      'Pause and squeeze the triceps.',
      'Let the bar return slowly until the elbows are bent again.',
      'Upper arms stay still. Squeeze the triceps at full extension.',
    ],
    reason: 'Source-bound side-view draft. Lying back on an incline bench facing away from a high pulley; the upper arms stay fixed beside the head while the elbows straighten from a right angle to fully extended, pause, and bend again more slowly. The pulley is placed where the forearms point at the start, so the cable only lengthens as the arms extend. Not drawn: the narrow overhand grip, which a side view cannot show; the bar reads end-on at the hands.',
    summary: 'Lying back on an incline bench facing away from a high pulley, straighten the elbows with the upper arms fixed beside the head, pause, then let the bar return slowly.',
  },
  {
    id: 179,
    slug: 'decline-dumbbell-triceps-extension',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly beside the ears."
    segments: [1700, 250, 1100, 500],
    captions: [
      'Secure the legs on a decline bench, lie back and hold a dumbbell in each hand above the chest, palms facing each other and arms straight.',
      'Keeping the upper arms still and the elbows in, bend the elbows to lower the dumbbells beside the ears.',
      'Upper arms stay still. Elbows point at the ceiling.',
      'Straighten the elbows to return the dumbbells above the chest.',
      'Arms straight above the chest again.',
    ],
    reason: 'Source-bound side-view draft. Lying back on a decline bench, head at the low end, knees over the high end and ankles hooked under a roller; the upper arms point up from the lying chest, 15 degrees back from plumb, and do not move while the elbows bend to bring the dumbbells down beside the ears, slowly, and straighten again. The palms-in grip is shown by each bell being seen along its length, square to the forearm. Not drawn: the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Lying back on a decline bench with the legs secured, lower the dumbbells beside the ears by bending only the elbows, then straighten the arms above the chest.',
  },
  {
    id: 180,
    slug: 'decline-ez-bar-triceps-extension',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly toward the forehead."
    segments: [1600, 250, 1000, 500],
    captions: [
      'Secure the legs on a decline bench, lie back and hold the EZ bar above the chest with a grip slightly narrower than shoulder width, arms straight.',
      'Keeping the upper arms still, bend the elbows to lower the bar toward the forehead.',
      'Upper arms stay still, elbows in, bar just above the forehead.',
      'Straighten the elbows to return the bar above the chest.',
      'Arms straight above the chest again.',
    ],
    reason: 'Source-bound side-view draft. Lying back on a decline bench with the legs secured under a roller; the upper arms point up from the lying chest, 15 degrees back from plumb, and stay still while the elbows bend to lower the EZ bar toward the forehead, slowly, stopping just above it, and straighten again. The bar is one implement through both hands and reads end-on with its cambered shaft. Not drawn: the grip width, which a side view cannot show; the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Lying back on a decline bench with the legs secured, lower the EZ bar toward the forehead by bending only the elbows, then straighten the arms above the chest.',
  },
  {
    id: 156,
    slug: 'cable-lying-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly to the forehead line." ... "return the bar above the chest and pause."
    segments: [1600, 250, 1000, 700],
    captions: [
      'Lie on a flat bench with your head toward a low pulley and hold the bar with a narrow overhand grip, arms straight above the chest.',
      'Keeping the upper arms still and the elbows in, bend the elbows to lower the bar until it is just above the forehead.',
      'Elbows in, upper arms pointing at the ceiling.',
      'Straighten the elbows to return the bar above the chest.',
      'Pause with the arms straight above the chest.',
    ],
    reason: 'Source-bound side-view draft. Lying on a flat bench with the head toward a low pulley, feet on the floor; the upper arms point at the ceiling and stay there while the elbows bend to lower the bar to just above the forehead, then straighten, with a pause at the top. The cable runs from the pulley past the end of the bench to the bar without crossing the bench or the head, and only lengthens as the arms straighten. Not drawn: the narrow overhand grip, which a side view cannot show.',
    summary: 'Lying on a flat bench with the head toward a low pulley, lower the bar to just above the forehead by bending only the elbows, then straighten the arms and pause.',
  },
  {
    id: 237,
    slug: 'low-cable-triceps-extension',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then let the elbows bend slowly back to a right angle."
    segments: [1100, 600, 1900, 500],
    captions: [
      'Lie face up on the bench of a seated row station, head toward the pulley, holding the rope ends with palms facing each other, upper arms pointing at the ceiling and elbows bent to a right angle.',
      'Keeping the upper arms still, straighten the elbows until the forearms are vertical.',
      'Squeeze with the forearms vertical.',
      'Let the elbows bend slowly back to a right angle.',
      'Upper arms point at the ceiling. Only the forearms move.',
    ],
    reason: 'Source-bound side-view draft. Face up on the low bench of a seated row station with the head toward the low pulley and a rope in the hands; the upper arms point at the ceiling and stay there while the forearms go from level, elbows at a right angle, to vertical, hold, and return slowly to a right angle and no further. The cable only lengthens as the arms straighten. Not drawn: the palms-in grip on the rope ends, which a side view cannot show.',
    summary: 'Face up on a row-station bench with the head toward the low pulley, straighten the elbows until the forearms are vertical, squeeze, then let them bend slowly back to a right angle.',
  },
  {
    id: 276,
    slug: 'spider-curl',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then lower slowly until the arms are straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Lie with the chest and stomach against the angled side of a preacher bench, feet on the floor, upper arms resting on the pad, arms straight.',
      'Keeping the upper arms on the pad, curl the bar up as far as you can.',
      'Squeeze at the top.',
      'Lower slowly until the arms are straight.',
      'Chest stays on the bench. Upper arms stay on the pad.',
    ],
    reason: 'Source-bound side-view draft. The source sets this up its own way, so the drawing follows it and not the usual hanging-arm spider curl: chest and stomach lie against the angled side of a preacher pad, feet on the floor, and the upper arms lie down the pad\'s other side with their backs resting on it. That far side is drawn sloping, square to the angled side: in this rig a plumb face cannot reach a hanging upper arm, so only the lower part of each upper arm is on the pad. They stay there while the bar is curled from straight arms as far as it goes, held, and lowered slowly to straight arms. Not drawn: the shoulder-width underhand grip, which a side view cannot show; the bar reads end-on at the hands.',
    summary: 'Chest and stomach against the angled side of a preacher bench, upper arms on the pad: curl the bar up as far as you can, squeeze, then lower slowly to straight arms.',
  },
  {
    id: 171,
    slug: 'concentration-curls',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then lower slowly until the arm is straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit on a flat bench with the feet wide, hold one dumbbell and rest the back of that upper arm against the inner thigh, arm straight, palm facing forward.',
      'Keeping the upper arm still, curl the dumbbell up toward the shoulder.',
      'Squeeze at the top.',
      'Lower slowly until the arm is straight.',
      'Complete the repetitions, then change arms.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model seen nearly from the front, turned 72 degrees, so the wide feet and the inner thigh both show. Seated on a flat bench, leaning forward, the back of the working upper arm rests against the inner thigh and stays there while the forearm curls the dumbbell from a straight arm up toward the shoulder, holds, and lowers slowly. Over the upper half of the curl the wrist keeps turning, so the dumbbell tilts with its little-finger end rising toward the same-side ear; that cue came from the owner on 8 October 2026 and is not in the catalogue text, so no caption states it. The free hand rests on the other knee; the source does not say where it goes. One side is shown; the last caption carries the change of arms.',
    summary: 'Seated with the feet wide and the back of the upper arm against the inner thigh, curl one dumbbell up toward the shoulder, squeeze, lower slowly to a straight arm, then change arms.',
  },
  {
    id: 268,
    slug: 'seated-dumbbell-palms-down-wrist-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly"
    segments: [1000, 300, 1700, 500],
    captions: [
      'Sit on the edge of a flat bench with the forearms resting on the thighs, palms facing down, wrists just past the knees. Let the wrists drop.',
      'Lift the backs of the hands as far as the range allows without the elbows moving.',
      'Keep the forearms flat and still.',
      'Lower slowly.',
      'When the elbows lift to help, reduce the load.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on the edge of a flat bench, leaning forward with the forearms level along the thighs and the wrists just past the knees; only the hands move, from dropped to lifted and slowly back, with the dumbbells held under the knuckles because the palms face down. Not drawn: a close-up of the hand. The catalogue asks for one, and this frame shows the whole seated figure, so the wrist movement is small on screen.',
    summary: 'Forearms flat on the thighs, palms down: let the wrists drop, lift the backs of the hands as far as they go without moving the elbows, then lower slowly.',
  },
  {
    id: 269,
    slug: 'seated-dumbbell-palms-up-wrist-curl',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Lower slowly into the stretch"
    segments: [1000, 300, 1700, 500],
    captions: [
      'Sit on the edge of a flat bench with the forearms resting on the thighs, palms facing up, wrists just past the knees. Let the wrists open under the load.',
      'Curl the palms up as far as the range allows without the elbows moving.',
      'Keep the forearms flat and still.',
      'Lower slowly into the stretch.',
      'When the elbows lift to help, reduce the load.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on the edge of a flat bench, leaning forward with the forearms level along the thighs and the wrists just past the knees; only the hands move, from open under the load to curled up and slowly back, with the dumbbells resting on top of the hands because the palms face up. Not drawn: a close-up of the hand. The catalogue asks for one, and this frame shows the whole seated figure, so the wrist movement is small on screen.',
    summary: 'Forearms flat on the thighs, palms up: let the wrists open, curl the palms up as far as they go without moving the elbows, then lower slowly into the stretch.',
  },
  {
    id: 164,
    slug: 'cable-wrist-curl',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower the bar slowly until the wrists are extended again."
    segments: [1000, 600, 1700, 500],
    captions: [
      'Sit on a bench facing a low pulley, grip the bar palms-up and rest the forearms on the thighs with the wrists just past the knees.',
      'Keeping the forearms still, curl the wrists up as far as they go.',
      'Pause at the top.',
      'Lower the bar slowly until the wrists are extended again.',
      'Forearms stay on the thighs. Only the wrists move.',
    ],
    reason: 'Source-bound side-view draft with a hand that bends at the wrist. Sitting on a bench facing a low pulley, forearms level along the thighs and the wrists just past the knees; only the hands move, curling the bar up from extended wrists, pausing, and lowering slowly. The pulley sits below the line of the dropped hands, so the cable only lengthens as the wrists curl. Not drawn: the shoulder-width grip, which a side view cannot show, and a close-up of the hand, which the catalogue asks for; this frame shows the whole seated figure.',
    summary: 'Seated facing a low pulley with the forearms on the thighs, curl the wrists up as far as they go, pause, then lower the bar slowly until the wrists are extended again.',
  },
  {
    id: 95,
    slug: 'sit-up',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "Roll down as slowly as you rose."
    segments: [1900, 300, 1900, 500],
    captions: [
      'Lie on your back with knees bent, feet flat, hands crossed on your chest.',
      'Curl your torso up one segment at a time until your chest meets your thighs.',
      'Exhale on the way up.',
      'Roll back down the same way, as slowly as you rose.',
      'Peel up one vertebra at a time.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Knees bent, feet flat, hands crossed on the chest; the trunk peels off the floor from the head end while the lower back is still down, then the whole curled trunk comes up until the chest meets the thighs, and it rolls back down the same way in the same time. The trunk is drawn along the curled spine, not as one stiff piece pivoting at the hips, which the source calls a different movement.',
    summary: 'Knees bent and feet flat, curl the torso up one segment at a time until the chest meets the thighs, then roll back down the same way.',
  },
  {
    id: 124,
    slug: 'tuck-crunch',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "Pause with the abdominals shortened, then lower both ends slowly."
    segments: [1100, 600, 1800, 500],
    captions: [
      'Lie on your back with the hips and knees bent and the arms reaching toward the feet.',
      'Bring the ribs and pelvis toward one another, curling the shoulders up as the knees travel slightly toward the chest.',
      'Pause with the abdominals shortened. Reach past the hips.',
      'Lower both ends slowly.',
      'Lower both ends on the same slow count.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Hips and knees bent with the shins level, arms reaching toward the feet; the upper spine curls so the shoulders come up while the knees travel a little toward the chest, a pause, then both ends lower slowly together. Not drawn: the pelvis tilting toward the ribs. The lower back stays on the floor in this drawing and the knees carry that half of the movement.',
    summary: 'Hips and knees bent, arms reaching toward the feet: curl the shoulders up as the knees travel slightly toward the chest, pause, then lower both ends slowly.',
  },
  {
    id: 72,
    slug: 'reverse-crunch',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "Lower the hips slow"
    segments: [1100, 250, 1900, 500],
    captions: [
      'Lie on your back with knees bent over your hips, hands flat beside you.',
      'Curl your hips off the floor, bringing the knees towards your ribs: the pelvis rolls up, the legs do not swing.',
      'Roll the pelvis up towards the ribs.',
      'Lower the hips back down slowly.',
      'Keep the feet floating between reps.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Knees bent over the hips, hands flat beside the body, shoulders on the floor; the lower spine curls so the pelvis rolls up and the hips leave the floor, with the legs riding on the pelvis and keeping their shape, then the hips lower more slowly. The feet stay off the floor for the whole cycle.',
    summary: 'Knees bent over the hips, roll the pelvis up so the hips leave the floor and the knees come towards the ribs, then lower the hips slowly without the feet touching down.',
  },
  {
    id: 99,
    slug: 'cable-reverse-crunch',
    equipment: 'cable_machine',
    phases: [0, 2, 2, 0, 0],
    // "Set the hips down on a slow count."
    segments: [1300, 300, 2000, 500],
    captions: [
      'Attach both ankles to a low cable, lie facing away from the stack, hips and knees near 90 degrees, shoulders heavy on the floor.',
      'Tuck the pelvis first, then curl the knees toward the ribs until the tailbone lifts without throwing the legs.',
      'Curl the knees toward the ribs.',
      'Set the hips down slowly while keeping cable tension.',
      'Start with the pelvis tucked.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying with the head away from the stack and a low cable to the ankles, hips and knees at right angles, shoulders on the floor; the pelvis tucks first, then the lower spine curls so the tailbone lifts and the knees come toward the ribs, with the legs riding on the pelvis, and the hips set down more slowly. The cable stays taut and only lengthens as the knees come in. Not drawn: the ankle cuffs; the cable ends at the ankle.',
    summary: 'Lying with a low cable on the ankles, tuck the pelvis, curl the knees toward the ribs until the tailbone lifts, then set the hips down slowly with the cable still tight.',
  },
  {
    id: 150,
    slug: 'bent-knee-hip-raise',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "Squeeze at the top for a second, then lower slowly to the start."
    segments: [1500, 1000, 2100, 500],
    captions: [
      'Lie flat on the floor with the arms beside you, knees bent to about seventy-five degrees and the feet a couple of inches up.',
      'Draw the knees toward the chest, holding that knee angle, until the pelvis rolls back and the hips leave the floor.',
      'Squeeze at the top for a second.',
      'Lower slowly to the start.',
      'Hold the knee angle throughout.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying flat with the arms beside the body, knees bent 75 degrees and the feet just clear of the floor; the knees are drawn toward the chest at that same knee angle, then the lower spine curls so the pelvis rolls back and the hips leave the floor, a one-second hold, and a slower return to the start.',
    summary: 'Lying flat with the knees bent and the feet just off the floor, draw the knees toward the chest at the same knee angle until the hips leave the floor, squeeze for a second, then lower slowly.',
  },
  {
    id: 183,
    slug: 'decline-reverse-crunch',
    equipment: 'bench',
    phases: [0, 2, 2, 0, 0],
    // "Pause, then lower the hips and return the legs slowly to the start."
    segments: [1500, 600, 2200, 500],
    captions: [
      'Lie on a decline bench with the head at the high end, hold the top of the bench and raise the legs, knees slightly bent, until they are level with the floor.',
      'Draw the knees toward the chest and roll the pelvis so the hips lift off the bench.',
      'Pause at the top. Hold the bench firmly.',
      'Lower the hips and return the legs slowly to the start.',
      'Legs level with the floor again, knees slightly bent.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Lying on a decline bench with the head at the high end and the hands holding the top of the bench; the legs start level with the floor with the knees slightly bent, the knees are drawn toward the chest, then the lower spine curls so the pelvis rolls and the hips lift off the bench, a pause, and a slower return. Not drawn: the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Head at the high end of a decline bench and hands on its top, draw the knees toward the chest and roll the pelvis so the hips lift off the bench, pause, then return slowly.',
  },
  {
    id: 285,
    slug: 'standing-rope-crunch',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then return slowly to standing tall."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Attach a rope to a high pulley, stand with your back to the machine and hold the rope ends over the shoulders against the upper chest.',
      'Keeping the hips still, curl the spine to crunch the torso down as far as you can control.',
      'Pause at the bottom. Rope stays at the upper chest.',
      'Return slowly to standing tall.',
      'Curl the spine, hips still.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls. Standing with the back to a high pulley and the rope ends held over the shoulders against the upper chest; the hips and legs do not move while the spine curls the trunk forward and down, a pause, and a slower return to standing tall. The hands travel with the upper chest, and the cable runs over the shoulder and only lengthens on the way down.',
    summary: 'Standing with your back to a high pulley and the rope at the upper chest, curl the spine to crunch the torso down with the hips still, pause, then return slowly to standing tall.',
  },
  {
    id: 232,
    slug: 'kneeling-cable-crunch-with-alternating-oblique-twists',
    equipment: 'cable_machine',
    phases: [0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
    turns: [0, 0, 0, 35, 35, 35, -35, -35, -35, 0],
    // "then rise slowly" on every repetition; the short gaps are the change of side at the top.
    segments: [1200, 1800, 250, 1200, 1800, 250, 1200, 1800, 250],
    captions: [
      'Attach a rope to a high pulley, kneel facing it a short step back and hold the rope ends beside the ears.',
      'Keeping the hands by the ears and the hips still, curl the torso down until the elbows reach the knees.',
      'Rise slowly.',
      'On the next repetition, turn partway down.',
      'One elbow travels to the opposite knee.',
      'Rise slowly.',
      'Then repeat to the other side.',
      'The other elbow travels to its opposite knee.',
      'Rise slowly.',
      'Hands stay by the ears. Curl the spine, hips still.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls and shoulders that turn. Kneeling facing a high pulley with the rope ends beside the ears; three repetitions in one cycle, as the source orders them: a plain curl down until the elbows reach the knees, then one that turns as it goes down so one elbow travels toward the opposite knee, then the same to the other side, each followed by a slow rise. The hips do not move and the hands stay by the ears throughout. Seen from the side, the turn shows as one shoulder and elbow leading and the other trailing.',
    summary: 'Kneeling facing a high pulley with the rope by the ears, curl down until the elbows reach the knees and rise slowly; on the next repetitions turn partway down so one elbow travels to the opposite knee, alternating sides.',
  },
  {
    id: 181,
    slug: 'decline-oblique-crunch',
    equipment: 'bench',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower slowly to the start."
    segments: [1300, 600, 2000, 500],
    captions: [
      'Secure the legs on a decline bench and lean back until the torso is partway down, one hand beside the head and the other on the thigh.',
      'Curl the torso up while turning it so the raised elbow travels toward the opposite knee.',
      'Pause at the top. Turn the ribs, lead with the shoulder.',
      'Lower slowly to the start.',
      'Complete the repetitions on one side, then change sides.',
    ],
    reason: 'Source-bound side-view draft with a spine that curls and shoulders that turn. Legs secured on a decline bench, torso partway down, one hand beside the head and the other on the thigh; the trunk curls up while the shoulders turn so the raised elbow travels toward the opposite knee, a pause, and a slower return. The hips stay on the bench. One side is shown; the last caption carries the change of sides. Seen from the side, the turn shows as the near shoulder and elbow coming forward. Not drawn: the decline angle is not given by the source, so 20 degrees is a drawing choice.',
    summary: 'Legs secured on a decline bench with the torso partway down, curl up while turning so the raised elbow travels toward the opposite knee, pause, lower slowly, then change sides.',
  },
  {
    id: 160,
    slug: 'cable-russian-twists',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then return slowly to the start with tension still on the cable."
    segments: [1300, 600, 2000, 500],
    captions: [
      'Lie with the upper back on a stability ball side-on to a mid-height pulley, the handle in both hands, arms straight above the chest and the hips raised.',
      'Keeping the hips up and the arms straight, turn the torso away from the pulley through a quarter turn.',
      'Pause. Arms straight, turn from the ribs.',
      'Return slowly to the start with tension still on the cable.',
      'Complete the repetitions, then turn around and repeat on the other side.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model turned 50 degrees so the turn can be seen. Upper back on a stability ball, hips raised with the feet flat, both hands on one handle above the chest, side-on to a mid-height pulley on the far side; the shoulders roll a quarter turn away from the pulley and the straight arms go with them, a pause, and a slower return. The hips stay up and still. One side is shown; the last caption carries the turn-around. This is the source\'s ball-supported movement, not a floor or seated Russian twist.',
    summary: 'Upper back on a stability ball with the hips raised and the arms straight above the chest, turn the torso a quarter turn away from the pulley, pause, return slowly, then repeat on the other side.',
  },
  {
    id: 248,
    slug: 'one-arm-high-pulley-cable-side-bends',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Return slowly to upright, keeping tension on the cable."
    segments: [1200, 300, 1900, 500],
    captions: [
      'Stand side-on to a high pulley with the handle pulled down until the elbow touches your side and the handle is by the shoulder, feet hip-width apart and the free hand on the hip.',
      'Keeping that arm fixed in place, bend sideways toward the cable side to pull the weight down.',
      'Arm stays fixed at the side. Bend from the waist.',
      'Return slowly to upright, keeping tension on the cable.',
      'Complete the repetitions, then change sides.',
    ],
    reason: 'Source-bound front-view draft with a spine that bends sideways. Standing side-on to a high pulley, the working elbow at the side with the handle by the shoulder and the free hand on the hip, feet hip-width apart; the hips and legs do not move while the trunk bends toward the cable side, the arms going with it without changing shape, and it returns more slowly to upright. The cable only lengthens as the trunk bends. One side is shown; the last caption carries the change of sides. Not drawn: the underhand grip.',
    summary: 'Standing side-on to a high pulley with the elbow at your side and the handle by the shoulder, bend sideways toward the cable with that arm fixed, then return slowly to upright and change sides.',
  },
  {
    id: 89,
    slug: 'floor-back-extension',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "hold a beat, then lower with control"
    segments: [1100, 600, 1700, 500],
    captions: [
      'Lie face-down with your arms reaching ahead.',
      'Lift your chest, arms, and legs a few inches off the floor by squeezing the glutes and upper back.',
      'Hold a beat. Reach long through fingers and toes.',
      'Lower with control.',
      'Reach long, then lift: length before height.',
    ],
    reason: 'Source-bound side-view draft with a spine that arches. Lying face down with the arms reaching ahead; the pelvis stays on the floor while the spine arches a little so the chest and arms come a few inches up, and the long legs lift a few inches from the hips, a short hold, and a slower lowering. The lift is kept small on purpose: the source says height is not the goal, and the trunk bends through its length; it is not launched up as one stiff piece.',
    summary: 'Face down with the arms reaching ahead, lift the chest, arms and legs a few inches off the floor, hold a beat, then lower with control.',
  },
  {
    id: 37,
    slug: 'bench-dip',
    equipment: 'bench',
    phases: [0, 1, 1, 0, 0],
    segments: [1500, 250, 1100, 500],
    captions: [
      'Grip the edge of a stable bench behind you, bend the knees, and keep the hips just clear of the edge.',
      'Bend the elbows straight back and lower only through the range the shoulders can hold comfortably.',
      'Elbows point straight back. Shoulders down, away from the ears.',
      'Press to long arms while keeping the hips close to the bench.',
      'Hips graze the bench the whole way.',
    ],
    reason: 'Source-bound side-view draft, in the source\'s beginner set-up: hands on the edge of a bench behind, knees bent and feet flat on the floor, hips just clear of the bench edge. The hips travel straight down and back up close to the bench while the elbows bend straight back to about a right angle and no further, then press to long arms. Not drawn: the later progression to straight legs.',
    summary: 'Hands on the edge of a bench behind you and knees bent, bend the elbows straight back to lower through a comfortable range, then press to long arms with the hips close to the bench.',
  },
  {
    id: 182,
    slug: 'decline-push-up',
    equipment: 'bench',
    phases: [0, 1, 1, 0, 0],
    segments: [1400, 200, 1100, 500],
    captions: [
      'Place the hands on the floor a little wider than the shoulders and the feet up on a bench, arms straight and the body in one line.',
      'Bend the elbows to lower the chest until it is just above the floor.',
      'Body in one straight line. Chest just above the floor.',
      'Press back up until the arms are straight.',
      'Push the floor away.',
    ],
    reason: 'Source-bound side-view draft. Feet up on a bench and hands on the floor with the arms straight; the body is one line from the ankles to the head that pivots about the feet as the elbows bend, lowering the chest to just above the floor, and presses back to straight arms. The feet stay on the bench and the hands stay where they are throughout. Not drawn: the hand width, which a side view cannot show.',
    summary: 'Feet up on a bench and hands on the floor, lower the chest to just above the floor with the body in one straight line, then press back up until the arms are straight.',
  },
  {
    id: 27,
    slug: 'road-run',
    equipment: 'none',
    phases: [0, 1, 2, 3, 4, 5, 6],
    // An even, relaxed cadence: one full stride, both feet, in about seven tenths of a second.
    segments: [115, 115, 115, 115, 115, 115],
    captions: [
      'Begin tall with the shoulders relaxed and a small whole-body lean from the ankles.',
      'Let each foot land quietly beneath the body.',
      'Push off, keeping the stride relaxed.',
      'Both feet leave the ground, then the other foot lands beneath the body.',
      'Keep the shoulders and hands relaxed.',
      'Settle into a pace you can hold.',
      'If breathing or form changes sharply, slow to a sustainable effort.',
    ],
    reason: 'Source-bound side-view draft of a stride run on the spot, since a preview cannot travel. Tall with a small forward lean; each leg goes through landing beneath the body, mid-stance, toe-off, heel coming up behind, knee driving through and reaching down to land, with the two legs half a stride apart and the arms swinging opposite the legs. Between each toe-off and the next landing both feet are off the ground. The pace is even through the stride. Not drawn: breathing and effort, which the source describes and a figure cannot show.',
    summary: 'Run tall with relaxed shoulders and a small lean from the ankles, each foot landing quietly beneath the body, at a pace you can hold.',
  },
  {
    id: 295,
    slug: 'upright-barbell-row',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower the bar slowly to the thighs."
    segments: [1100, 500, 1900, 500],
    captions: [
      'Stand tall holding a barbell against the thighs with an overhand grip slightly narrower than the shoulders.',
      'Keeping the bar close to the body, lift it toward the chin by raising the elbows up and out to the sides, elbows higher than the hands.',
      'Pause at the top. Elbows lead and stay above the hands.',
      'Lower the bar slowly to the thighs.',
      'Bar stays close to the body.',
    ],
    reason: 'Source-bound front-view draft. Standing tall with the bar against the thighs and the hands slightly narrower than the shoulders; the hands travel straight up the front of the body toward the chin while the elbows rise up and out to the sides and finish higher than the hands, a pause, and a slower lowering to the thighs. The trunk and legs do not move. Drawn from a 3D model: with a narrow grip the elbows cannot be straight out to the sides, so they come up and out a little forward of the shoulders, which a front view shows as out. Not drawn: how close the bar is to the body, which only a side view shows, and the overhand grip.',
    summary: 'Standing tall with a narrow overhand grip, lift the bar from the thighs toward the chin with the elbows leading up and out, higher than the hands, pause, then lower slowly.',
  },
  {
    id: 297,
    slug: 'upright-row-with-bands',
    equipment: 'band',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower slowly to the thighs." / "Lower slowly against the band."
    segments: [1200, 600, 2000, 500],
    captions: [
      'Stand on the middle of a band and hold an end in each hand against the thighs with the palms facing the body.',
      'Keeping the hands close to the body, lift them toward the chin by raising the elbows up and out to the sides, elbows higher than the hands.',
      'Pause at the top. Elbows lead and stay above the hands.',
      'Lower slowly to the thighs, against the band.',
      'Hands stay close to the body.',
    ],
    reason: 'Source-bound front-view draft. Standing on the middle of a band with an end in each hand against the thighs; the hands travel straight up the front of the body toward the chin while the elbows rise up and out to the sides and finish higher than the hands, a pause, and a slower lowering against the band. Each end of the band runs from under a foot to the hand above it and stretches as the hands rise. The trunk and legs do not move. Not drawn: how close the hands are to the body, which only a side view shows, and the palms facing the body.',
    summary: 'Standing on a band with an end in each hand, lift the hands from the thighs toward the chin with the elbows leading up and out, higher than the hands, pause, then lower slowly.',
  },
  {
    id: 139,
    slug: 'barbell-side-split-squat',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    segments: [1400, 250, 1200, 500],
    captions: [
      'Stand tall with a barbell across the back of the shoulders and the feet placed wide apart, the lead foot angled out to the side.',
      'Bend the knee and hip of the lead leg to lower toward that side, keeping the trailing leg only slightly bent.',
      'Shift toward the working side. Keep the trailing leg long.',
      'Return by extending the hip and knee of the lead leg.',
      'Complete the reps on one side, then work the other.',
    ],
    reason: 'Source-bound front-view draft. Standing tall with the bar across the back of the shoulders and the feet planted wide; the hips travel down and toward the lead foot as the lead knee and hip bend, the lead knee coming forward over its foot, while the trailing leg stays long with only a slight bend, and the lead leg straightens to return. Both feet stay where they are. One side is shown; the last caption carries the change of sides. Not drawn: the lead foot angled out, which this front-view foot cannot show; the caption states it.',
    summary: 'Feet wide and the bar across the back of the shoulders, bend the lead knee and hip to lower toward that side with the trailing leg long, then extend the lead leg to return.',
  },
  {
    id: 162,
    slug: 'cable-seated-lateral-raise',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower the arms slowly to the start."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit on the end of a flat bench between two low pulleys, lean forward so the chest rests toward the thighs with the back flat, and hold the left handle in the right hand and the right handle in the left.',
      'With a slight, fixed bend in the elbows, raise the upper arms out to the sides until they are level with the shoulders.',
      'Pause at the top. Lead with the elbows.',
      'Lower the arms slowly to the start.',
      'Back flat, chest toward the thighs. Keep the elbow bend fixed.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model turned 65 degrees so the seat, the forward lean and both arms show. Sitting on the end of a flat bench between two low pulleys, leaning forward from the hips with the back flat, each hand holding the handle from the opposite pulley so the cables cross under the chest; the arms raise out to the sides with one slight fixed elbow bend until the upper arms are level with the shoulders, pause, and lower more slowly. The trunk and legs do not move. Each cable only lengthens as its arm rises.',
    summary: 'Seated between two low pulleys and leaning forward with a flat back, raise the arms out to the sides with a fixed slight elbow bend until level with the shoulders, pause, then lower slowly.',
  },
  {
    id: 261,
    slug: 'reverse-flyes',
    equipment: 'dumbbells',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze the shoulder blades together, then lower under control."
    segments: [1200, 600, 1700, 500],
    captions: [
      'Lie chest-down on an incline bench with a dumbbell in each hand, palms facing each other, arms hanging perpendicular to the bench.',
      'Holding a slight bend at the elbows, move the weights out and away from each other in an arc until the arms are parallel to the floor.',
      'Squeeze the shoulder blades together.',
      'Lower under control.',
      'Keep the chest on the bench.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model turned 40 degrees so both arms and the bench show. Chest down on a bench inclined at 45 degrees with the feet on the floor; the arms start hanging square to the bench and sweep out and apart in one arc, with one slight fixed elbow bend, until the upper arms are parallel to the floor, hold, and lower more slowly. The chest stays on the bench. Not drawn: the bench angle is not given by the source, so 45 degrees is a drawing choice; the shoulder blades squeezing together, which this figure has no way to show.',
    summary: 'Chest down on an incline bench, sweep the dumbbells out and apart with a slight elbow bend until the arms are parallel to the floor, squeeze the shoulder blades, then lower under control.',
  },
  {
    id: 131,
    slug: 'back-flyes-with-bands',
    equipment: 'band',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then let the hands return slowly to the front."
    segments: [1100, 500, 1900, 500],
    captions: [
      'Loop a band around a rack upright, take an end in each hand and step back until the band is taut with the arms straight in front at shoulder height.',
      'Keeping the arms straight and level with the floor, pull the hands apart and back until the arms are out to the sides.',
      'Pause. Squeeze the shoulder blades together.',
      'Let the hands return slowly to the front.',
      'Arms straight and level with the floor.',
    ],
    reason: 'Source-bound draft, drawn from a 3D model turned 32 degrees and looked down on by 18, so the arms opening can be seen: the whole movement is in one level plane at shoulder height, which any level viewpoint flattens to a line. Because the view looks down, the nearer foot and the upright in front sit a little lower on the page than the farther foot. Standing facing a rack upright with a band looped round it at shoulder height and an end in each hand; the straight arms stay level with the floor and open from in front of the shoulders to out at the sides, pause, and return more slowly. Each end of the band runs from the upright to a hand and stretches as the hands part. This is the source\'s standing movement; the catalogue family name still says supine.',
    summary: 'Standing with a band looped round a rack upright at shoulder height, pull the straight, level arms apart and back until they are out to the sides, pause, then return slowly to the front.',
  },
  {
    id: 161,
    slug: 'cable-seated-crunch',
    previewId: 'cable_seated_crunch',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then return slowly to sitting tall."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit on a flat bench with your back to a high pulley and hold the rope ends over the shoulders against the upper chest.',
      'Keeping the hips still, curl the torso forward so the elbows travel toward the hips.',
      'Pause. Curl the ribs toward the hips.',
      'Return slowly to sitting tall, against the cable.',
      'Hips stay still.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the athlete lying on the floor. Source-bound side-view draft with a spine that curls: sitting on a flat bench with the back to a high pulley, rope ends over the shoulders at the upper chest; the hips and legs do not move while the spine curls the trunk forward and the elbows travel toward the hips, a pause, and a slower return to sitting tall. The cable runs over the shoulder and only lengthens on the way down.',
    summary: 'Sitting on a bench with your back to a high pulley and the rope at the upper chest, curl the torso forward with the hips still, pause, then return slowly to sitting tall.',
  },
  {
    id: 39,
    slug: 'cable-crunch',
    previewId: 'cable_crunch',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Unroll slowly until the abs are on stretch"
    segments: [1200, 400, 2000, 500],
    captions: [
      'Kneel far enough from the stack that the cable stays loaded at the top, rope held to your collarbones.',
      'Crunch by rounding your upper spine, driving your elbows towards your thighs while your hips stay frozen.',
      'Round the upper spine, elbows to the thighs.',
      'Unroll slowly until the abs are on stretch.',
      'Hips locked in place. Abs pull, arms just hold the rope.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed a stiff trunk hinging forward at the hips. Source-bound side-view draft with a spine that curls: kneeling facing a high pulley with the rope at the collarbones; the hips and the lower back do not move while the upper spine rounds and the elbows travel toward the thighs, then it unrolls more slowly. The figure kneels leaning toward the pulley, which is high and a short way in front, so the cable only lengthens on the way down.',
    summary: 'Kneeling with the rope at your collarbones, round the upper spine to drive the elbows toward the thighs with the hips frozen, then unroll slowly.',
  },
  {
    id: 173,
    slug: 'cross-body-crunch',
    previewId: 'cross_body_crunch',
    equipment: 'none',
    phases: [1, 0, 0, 1, 2, 2, 1],
    // "Lower slowly to the start, then repeat to the other side."
    segments: [1100, 300, 1700, 1100, 300, 1700],
    captions: [
      'Lie on your back with the knees bent and the feet flat, hands resting lightly behind the head.',
      'Curl up and turn so one elbow and shoulder travel across the body while the opposite knee comes in to meet them.',
      'Lead with the shoulder. Curl the ribs toward the hips.',
      'Lower slowly to the start.',
      'Then repeat to the other side.',
      'The other shoulder leads and the other knee comes in to meet it.',
      'Lower slowly to the start.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed straight legs and no knee coming in. Source-bound side-view draft with a spine that curls and shoulders that turn: knees bent, feet flat, hands by the head; the upper spine curls and turns so one shoulder and elbow lead across the body while the opposite knee comes in to meet them, a slower lowering, then the same to the other side. Seen from the side, the turn shows as one shoulder and elbow leading; the catalogue asks for a front view as well. The hands are drawn at the sides of the head: this figure cannot put a hand between the head and the floor.',
    summary: 'Knees bent and feet flat, curl up and turn so one elbow and shoulder travel across while the opposite knee comes in to meet them, lower slowly, then repeat to the other side.',
  },
  {
    id: 226,
    slug: 'janda-sit-up',
    previewId: 'janda_sit_up',
    equipment: 'none',
    phases: [0, 2, 2, 0, 0],
    // "over a slow three to six second count" ... "across a matching count"
    segments: [3600, 300, 3600, 500],
    captions: [
      'Lie on your back with the knees bent to about ninety degrees and the feet flat on the floor, arms resting at your sides.',
      'Tighten the glutes and hamstrings hard, hold that tension, and curl the trunk up over a slow three to six second count.',
      'Hold that tension for the whole rep.',
      'Lower back down under the same tension across a matching count.',
      'Take the descent as slowly as the climb.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed straight legs. Source-bound side-view draft with a spine that curls: knees bent to a right angle with the feet flat and the arms at the sides; the trunk peels off the floor and curls up over three and a half seconds, and lowers the same way over the same time. Not drawn: the glutes and hamstrings held tight, which is the point of the movement and which a figure cannot show; the captions carry it.',
    summary: 'Knees bent to ninety degrees and feet flat, hold the glutes and hamstrings tight and curl the trunk up over a slow count, then lower over a matching count.',
  },
  {
    id: 25,
    slug: 'pallof-press',
    previewId: 'pallof_press',
    equipment: 'band',
    phases: [0, 1, 1, 0, 0],
    // "Pause before returning to the chest"
    segments: [900, 1200, 1100, 500],
    captions: [
      'Stand side-on to an anchored band and hold it at the centre of the chest in a stable stance.',
      'Press to long arms while the shoulders and hips stay square.',
      'Pause. Breathe through the hold.',
      'Return to the chest.',
      'Keep the shoulders and hips square.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the band anchored behind the athlete\'s back. Source-bound draft, drawn from a 3D model turned 60 degrees so the anchor is seen out to the athlete\'s side: standing side-on to an anchored band held at the centre of the chest; the hands press straight out to long arms, hold, and return, and nothing else moves. The band stretches a little as the hands go out.',
    summary: 'Standing side-on to an anchored band held at the chest, press to long arms with the shoulders and hips square, pause, then return to the chest.',
  },
  {
    id: 251,
    slug: 'pallof-press-with-rotation',
    previewId: 'pallof_press_with_rotation',
    equipment: 'cable_machine',
    phases: [0, 1, 2, 2, 1, 0],
    // "Return slowly to face forward and bring the handle back to the chest."
    segments: [800, 1100, 500, 1700, 900],
    captions: [
      'Set the pulley at shoulder height, stand side-on to it with the feet hip-width apart and hold the handle in both hands at the chest.',
      'Press the handle straight out.',
      'Keeping the hips still and the arms straight, turn the torso away from the pulley through a quarter turn.',
      'Arms straight, turn from the ribs.',
      'Return slowly to face forward.',
      'Bring the handle back to the chest, then face the other way after the set.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the pulley behind the athlete\'s back. Source-bound draft, drawn from a 3D model turned 60 degrees so the pulley is seen out to the athlete\'s side: standing side-on to a shoulder-height pulley with the handle at the chest; press straight out, then the shoulders turn a quarter turn away from the pulley with the arms straight and the hips and legs still, a pause, a slower return to face forward, and the handle comes back to the chest. The cable only lengthens through the press and the turn. One side is shown; the last caption carries the change of sides.',
    summary: 'Standing side-on to a shoulder-height pulley, press the handle straight out, turn the torso a quarter turn away with the arms straight and the hips still, then return slowly and bring the handle back to the chest.',
  },
  {
    id: 40,
    slug: 'cable-pull-through',
    previewId: 'cable_pull_through',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    segments: [1400, 250, 1100, 600],
    captions: [
      'Face away from a low cable with a rope between your legs, held at your hips, and walk out until the cable is taut.',
      'Push your hips back and hinge forward with a flat back.',
      'Push the hips back: the arms just hold the rope.',
      'Drive your hips forward to stand tall.',
      'Squeeze your glutes at lockout.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the cable running to a pulley in front of the athlete. Source-bound side-view draft: facing away from a low pulley with the rope held at the hips and the cable running back between the legs; the hips go back and the flat back hinges forward over soft knees with the feet planted, then the hips drive forward to stand tall. The cable is drawn behind the near leg and only lengthens as the athlete stands.',
    summary: 'Facing away from a low cable with the rope between your legs, push the hips back and hinge with a flat back, then drive the hips forward to stand tall.',
  },
  {
    id: 286,
    slug: 'step-up-with-knee-raise',
    previewId: 'step_up_with_knee_raise',
    equipment: 'bench',
    phases: [0, 2, 3, 3, 2, 0, 0],
    segments: [900, 1200, 400, 1300, 900, 400],
    captions: [
      'Stand facing a box or bench of a height you can control, feet together.',
      'Step up by placing one whole foot on the top.',
      'Extend the hip and knee to stand tall, and as you stand drive the opposite knee up as high as you can.',
      'Stand tall before the knee comes up.',
      'Reverse the motion to step down, under control.',
      'Feet together on the floor again.',
      'Repeat on the other leg.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the free leg swinging out behind and the athlete never standing tall. Source-bound side-view draft: feet together facing a box; one whole foot is placed on the top, the hip and knee extend to stand tall on the box as the opposite knee drives up, a short hold, and the motion reverses to step down. The stepping foot stays where it is placed and the floor foot does not jump. One side is shown; the last caption carries the change of legs.',
    summary: 'Facing a box, place one whole foot on top, stand tall and drive the opposite knee up as high as you can, then reverse to step down and repeat on the other leg.',
  },
  {
    id: 115,
    slug: 'cable-internal-rotation',
    previewId: 'cable_internal_rotation',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "then pause when the hand reaches the centreline"
    segments: [1100, 600, 1500, 500],
    captions: [
      'Set a single cable handle around elbow height and stand side-on with the working elbow bent to 90 degrees and resting lightly against the ribs.',
      'Rotate the forearm across the torso while the upper arm stays quiet.',
      'Pause when the hand reaches the centreline.',
      'Return until the forearm points toward the cable.',
      'Rotate around a quiet upper arm.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the free arm mirroring the working one. Source-bound front-view draft: the cable is out to the working side at elbow height; the working upper arm hangs still at the side with the elbow at a right angle, and the level forearm turns from pointing at the cable to the centreline, pauses, and returns. The free arm hangs still. The cable only lengthens as the forearm turns in.',
    summary: 'Side-on to a cable at elbow height with the elbow bent ninety degrees at your ribs, rotate the forearm across the torso to the centreline, pause, then return until it points at the cable.',
  },
  {
    id: 224,
    slug: 'internal-rotation-with-band',
    previewId: 'internal_rotation_with_band',
    equipment: 'band',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then let it return slowly to the start."
    segments: [1200, 500, 1900, 500],
    captions: [
      'Fix a band at elbow height, stand side-on to it with the near elbow pressed to your side and bent to a right angle, the forearm pointing out away from the body.',
      'Keeping the elbow at your side, rotate the forearm in across the body as far as you can.',
      'Pause. Elbow stays pinned to the side.',
      'Let it return slowly to the start.',
      'Complete the repetitions, then change sides.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the free arm mirroring the working one. Source-bound front-view draft: a band fixed out to the working side at elbow height; the near upper arm stays at the side with the elbow at a right angle, and the level forearm turns from pointing out at the band to across the body, pauses, and returns more slowly. The free arm hangs still. One side is shown; the last caption carries the change of sides.',
    summary: 'Side-on to a band at elbow height with the near elbow pinned to your side, rotate the forearm in across the body as far as you can, pause, return slowly, then change sides.',
  },
  {
    id: 238,
    slug: 'low-pulley-row-to-neck',
    previewId: 'low_pulley_row_to_neck',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then return slowly until the arms are straight."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Sit at a low cable row station holding the rope ends with the palms facing down, back upright, knees slightly bent and arms straight in front.',
      'Keeping the torso still, lift the elbows and pull the rope toward the neck until the hands are beside the ears and the upper arms are level with the floor.',
      'Pause. Elbows high and wide.',
      'Return slowly until the arms are straight.',
      'Torso stays upright and still.',
    ],
    reason: 'Redrawn on 8 October 2026 at the owner\'s request, because the earlier drawing contradicted this text: it showed the athlete standing. Source-bound draft, drawn from a 3D model turned 35 degrees so the wide elbows show: sitting at a low row station with the back upright, the feet on the plate and the knees slightly bent, arms straight toward the low pulley; the elbows lift high and wide and the rope comes to the neck until the hands are beside the ears and the upper arms are level, a pause, and a slower return to straight arms. The trunk and legs do not move. Not drawn: the palms-down grip.',
    summary: 'Seated at a low cable row with the back upright, lift the elbows high and wide to pull the rope to the neck, hands beside the ears, pause, then return slowly to straight arms.',
  },
  {
    id: 142,
    slug: 'bent-over-barbell-row',
    previewId: 'bent_over_barbell_row',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze the back, then lower the bar slowly to a full hang."
    segments: [1100, 600, 1900, 500],
    captions: [
      'Hold a barbell with an overhand grip, bend the knees slightly and hinge forward with the back straight until the torso is almost level with the floor and the bar hangs under the shoulders.',
      'Keeping the torso still and the elbows close to the body, pull the bar up to the body.',
      'Squeeze the back. Lead with the elbows.',
      'Lower the bar slowly to a full hang.',
      'Back straight, torso still.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the torso was held about 40 degrees above level. Source-bound side-view draft: hinged over soft knees with a straight back until the trunk is almost level, the bar hanging under the shoulders on straight arms; the trunk and legs do not move while the bar is pulled up and back to the body with the elbows leading, a squeeze, and a slower lowering to a full hang. The bar is seen end-on. Not drawn: the overhand grip.',
    summary: 'Hinged forward with a straight back until the torso is almost level, pull the bar from a full hang up to the body with the torso still, squeeze, then lower slowly.',
  },
  {
    id: 110,
    slug: 'barbell-rear-delt-row',
    previewId: 'barbell_rear_delt_row',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "holding long enough to feel the rear shoulders finish. Lower to long arms without rising"
    segments: [1100, 800, 1700, 500],
    captions: [
      'Take a wide overhand grip, soften the knees, and hinge until the bar hangs beneath a braced torso.',
      'Drive the elbows wide and row the bar toward the upper chest.',
      'Hold long enough to feel the rear shoulders finish.',
      'Lower to long arms without rising.',
      'Brace the hinge before the pull. Drive the elbows wide.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the athlete began standing upright and the bar finished near the stomach, which the text names as the fault. Source-bound draft, drawn from a 3D model turned 40 degrees so the wide grip and the wide elbows show: hinged over soft knees with the bar hanging beneath the shoulders on a wide grip; the trunk does not rise while the elbows drive out to the sides and the bar is rowed to the upper chest, a hold, and a slower lowering to long arms. Not drawn: the overhand grip.',
    summary: 'Hinged with a wide grip and the bar hanging under a braced torso, drive the elbows wide to row the bar to the upper chest, hold, then lower to long arms without rising.',
  },
  {
    id: 144,
    slug: 'bent-over-one-arm-long-bar-row',
    previewId: 'bent_over_one_arm_long_bar_row',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze, then lower slowly without letting the plates rest on the floor."
    segments: [1100, 600, 1900, 500],
    captions: [
      'Load one end of a barbell and brace the other end in a corner, then hinge forward with the knees slightly bent, grip the bar just behind the plates with one hand and rest the other hand on the knee.',
      'Keeping the torso still and the elbow in, pull the bar straight up until the plates reach the lower chest.',
      'Squeeze. Elbow close to the body.',
      'Lower slowly without letting the plates rest on the floor.',
      'Complete the repetitions, then change arms.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: no bar or plates were drawn. Source-bound side-view draft: one end of the bar is braced on the floor behind the athlete and the loaded end is in front; hinged over slightly bent knees, the near hand grips the shaft just behind the plates and the free hand rests on the thigh above the knee. The trunk does not move while the bar swings up about its braced end until the plates reach the lower chest, a squeeze, and a slower lowering that stops short of the floor. One arm is shown; the last caption carries the change of arms.',
    summary: 'Hinged beside a bar braced at its far end, one hand just behind the plates and the other on the knee, pull the bar up until the plates reach the lower chest, squeeze, lower slowly, then change arms.',
  },
  {
    id: 287,
    slug: 'stiff-leg-barbell-good-morning',
    previewId: 'stiff_leg_barbell_good_morning',
    equipment: 'barbell',
    phases: [0, 1, 1, 0, 0],
    // Down under control, a brief turn, then "Bring the hips forward to stand tall again."
    segments: [1900, 300, 1500, 600],
    captions: [
      'Take the bar from the rack across the back of the shoulders and stand with the feet shoulder-width apart, back straight and head up.',
      'Keeping the legs still, push the hips back and lower the torso until it is about level with the floor.',
      'Back straight, ribs down.',
      'Bring the hips forward to stand tall again.',
      'Hips back, legs still. Stand tall through the hips.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the knees bent a good deal and the torso stopped well short of level. Source-bound side-view draft: the bar lies across the back of the shoulders with the hands on it; the hips travel back and the straight trunk lowers until it is about level with the floor, then the hips come forward to stand tall. The knees keep the one soft bend they start with for the whole rep, so the legs only lean back with the hips. The bar is seen end-on. Not drawn: the rack, and the shoulder-width stance, which a side view cannot show.',
    summary: 'With the bar across the back of the shoulders and the legs still, push the hips back and lower a straight torso to about level with the floor, then bring the hips forward to stand tall.',
  },
  {
    id: 22,
    slug: 'cable-row',
    previewId: 'cable_row',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Drive the elbows toward the back pockets, then return slowly"
    segments: [1100, 400, 1900, 500],
    captions: [
      'Sit at the cable row with the feet planted and the handle held in long arms.',
      'Drive the elbows toward the back pockets.',
      'Keep the torso tall and quiet.',
      'Return slowly, reaching the shoulder blades forward.',
      'If the torso rocks, reduce the load before shortening the reach.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: it showed a chair-height seat with the cable coming up from the floor. Source-bound side-view draft: sitting tall at a low row station with the feet planted on the plate and the handle in long arms toward the low pulley; the trunk does not rock while the elbows drive down and back and the handle comes to the lower ribs, then a slower return to long arms. The cable only lengthens on the pull. Not drawn: the shoulder blades reaching forward at the end of the return.',
    summary: 'Sitting tall at the cable row with the feet planted, drive the elbows toward the back pockets from long arms, then return slowly without the torso rocking.',
  },
  {
    id: 266,
    slug: 'seated-cable-rows',
    previewId: 'seated_cable_rows',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "Squeeze the back, then let the handle return slowly until the arms are straight."
    segments: [1100, 600, 1900, 500],
    captions: [
      'Sit at a low cable row station with the feet on the foot plate and the knees slightly bent, hold the V-handle and sit upright with the arms straight and the chest up.',
      'Keeping the torso still and the arms close to the body, pull the handle to the stomach.',
      'Squeeze the back. Drive the elbows back past the ribs.',
      'Let the handle return slowly until the arms are straight.',
      'Torso stays upright and still.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: no seat was drawn and the legs ran steeply down to the foot plate. Source-bound draft, drawn from a 3D model turned 35 degrees so the two hands on one V-handle show: sitting upright on the seat of a low row station with the feet on the plate and the knees slightly bent, arms straight; the trunk and legs do not move while the handle is pulled to the stomach with the arms close to the body and the elbows passing back beside the ribs, a squeeze, and a slower return to straight arms.',
    summary: 'Seated upright at a low cable row with the feet on the plate, pull the V-handle to the stomach with the arms close to the body, squeeze, then let it return slowly to straight arms.',
  },
  {
    id: 59,
    slug: 'face-pull',
    previewId: 'face_pull',
    equipment: 'cable_machine',
    phases: [0, 1, 1, 0, 0],
    // "hold a one-second squeeze with the shoulder blades pinned"
    segments: [1100, 1000, 1500, 500],
    captions: [
      'Set the rope at upper-chest height, grab it thumbs-back, and step away until the stack is live.',
      'Pull the rope to the bridge of your nose while splitting your hands past your ears, letting the shoulders rotate back at the end.',
      'Squeeze the blades for a full beat.',
      'This never becomes a heavy movement.',
      'Thumbs to the ears, elbows high. The weight stays humble.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the rope was anchored below upper-chest height. Source-bound draft, drawn from a 3D model turned 35 degrees so the hands splitting apart show: standing facing a pulley set at upper-chest height with the arms long toward it; the elbows go high and wide and the two rope ends split to finish beside the ears with the forearms turned up and back, a one-second squeeze, and a return to long arms. The trunk and legs do not move. Not drawn: the thumbs-back grip.',
    summary: 'Facing a rope set at upper-chest height, pull it to the bridge of the nose while the hands split past the ears with the elbows high, squeeze for a beat, then return to long arms.',
  },
  {
    id: 118,
    slug: 'calf-raises-with-bands',
    previewId: 'calf_raises_with_bands',
    equipment: 'band',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower into an owned stretch"
    segments: [1100, 700, 1700, 500],
    captions: [
      'Stand on the middle of a long band with the handles held at shoulder height and the feet set about hip width.',
      'Root the forefeet and rise as high as the ankles allow while the hands stay quiet beside the shoulders.',
      'Pause. Own the top.',
      'Lower slowly into an owned stretch.',
      'If the hands bob to manufacture height, the calves have stopped driving the rep.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the hands were held about waist height. Source-bound side-view draft: standing on a band with a handle in each hand beside the shoulders; the forefeet stay planted and the heels rise as far as the ankles allow, so the whole body lifts with straight legs, a pause, and a slower lowering. The hands do not move against the shoulders, and the band only stretches as the body rises. Not drawn: the hip-width stance, which a side view cannot show.',
    summary: 'Standing on a band with the handles beside the shoulders, root the forefeet and rise as high as the ankles allow with the hands quiet, pause, then lower slowly.',
  },
  {
    id: 174,
    slug: 'crunch-hands-overhead',
    previewId: 'crunch_hands_overhead',
    equipment: 'none',
    phases: [0, 1, 1, 0, 0],
    // "Pause, then lower slowly to the start."
    segments: [1200, 600, 1900, 500],
    captions: [
      'Lie on your back with the knees bent and the feet flat, arms stretched overhead with the hands together.',
      'Keeping the arms in line with the head, curl the upper body up until the shoulder blades are just off the floor.',
      'Pause. Curl the ribs toward the hips.',
      'Lower slowly to the start.',
      'Arms stay in line with the head.',
    ],
    reason: 'Redrawn on 9 October 2026 at the owner\'s request, because the earlier drawing was against this text: the trunk lifted as one stiff piece. Source-bound side-view draft with a spine that curls: lying with the knees bent and the feet flat, arms long beside the head; the hips and the lower back stay on the floor while the upper spine curls until the shoulder blades are just off it, the arms staying in line with the head, a pause, and a slower lowering. Not drawn: the hands together, which a side view cannot show.',
    summary: 'Lying with the knees bent and the arms stretched overhead, curl the upper body up until the shoulder blades are just off the floor with the arms in line with the head, pause, then lower slowly.',
  },
];
