/** Independent actual component probes. Covered statuses are isolated fixtures, never approval. */
const React=require('react'),testing=require('@testing-library/react-native'),fs=require('node:fs'),path=require('node:path');
const {render,act,fireEvent,cleanup}=testing,screen=new Proxy({},{get:(_,key)=>testing.screen[key]});
const {AccessibilityInfo,AppState,StyleSheet}=require('react-native');
const root=path.resolve(__dirname,'../../..');
if(process.env.AUDIT_PRIOR_GEOMETRY==='1')jest.doMock(root+'/apps/mobile/src/components/movementPreview/canonicalFigure',()=>require('./prior-canonicalFigure.js'));
const {MovementPreview}=require(root+'/apps/mobile/src/components/movementPreview/MovementPreview');
const manifest=require(root+'/apps/mobile/src/components/movementPreview/manifest'),coordinator=require(root+'/apps/mobile/src/components/movementPreview/playbackCoordinator');
const {DUAL_BODY_PARAMETERS,poseAtTime}=require(root+'/apps/mobile/src/components/movementPreview/canonicalFigure');
const {theme}=require(root+'/apps/mobile/src/theme/theme');
const raw=require(root+'/apps/mobile/src/components/movementPreview/movementPreviewManifest.json');
const fixtures=new Map([52,53].map(id=>[id,manifest.buildPreviewEntry({...raw.entries.find(e=>e.movementId===id),status:'covered'})]));
const subject=id=>({movement_id:id,media:{assetKey:fixtures.get(id).assetKey,status:'ready'}});
const control=()=>screen.getByTestId('movement-preview-control'),stage=()=>screen.getByTestId('movement-preview-stage-canonical');
const styles=()=>React.Children.toArray(stage().props.children).map(c=>StyleSheet.flatten(c.props.style));
const drawing=()=>JSON.stringify(styles()),near=(a,b)=>Math.abs(a-b)<1e-7,rad=d=>d*Math.PI/180;
const measurements=[];
function bounds(s){const theta=rad(parseFloat(s.transform?.find(t=>t.rotate!==undefined)?.rotate??'0')),r=Math.min(s.borderRadius??0,s.width/2,s.height/2),cx=s.left+s.width/2,cy=s.top+s.height/2;return {left:cx-(s.width/2-r)*Math.abs(Math.cos(theta))-(s.height/2-r)*Math.abs(Math.sin(theta))-r,right:cx+(s.width/2-r)*Math.abs(Math.cos(theta))+(s.height/2-r)*Math.abs(Math.sin(theta))+r,top:cy-(s.width/2-r)*Math.abs(Math.sin(theta))-(s.height/2-r)*Math.abs(Math.cos(theta))-r,bottom:cy+(s.width/2-r)*Math.abs(Math.sin(theta))+(s.height/2-r)*Math.abs(Math.cos(theta))+r};}
const noMotion=()=>{act(()=>jest.runAllTicks());expect(jest.getTimerCount()).toBe(0);expect(coordinator.isPlaybackActive()).toBe(false);};
function inspect(bodyName,phase,sample){const all=styles(),surface=StyleSheet.flatten(stage().props.style),entry=fixtures.get(52),body=DUAL_BODY_PARAMETERS[bodyName],scale=Math.min(240/entry.frameData.viewBox[2],240/entry.frameData.viewBox[3]);const floor=all.find(s=>s.height===1&&s.right===0&&s.backgroundColor===theme.color.line);expect(floor).toBeDefined();
 let maxCropExcess=0;for(const s of all){if(s.width===undefined||s.height===undefined||s.opacity===0)continue;expect([s.left,s.top,s.width,s.height].every(Number.isFinite)).toBe(true);const b=bounds(s);maxCropExcess=Math.max(maxCropExcess,0,-b.left,-b.top,b.right-surface.width,b.bottom-surface.height);}expect(maxCropExcess).toBeLessThanOrEqual(.05);
 const feet=all.filter(s=>s.transform&&near(s.width,5.4*scale)&&near(s.height,body.lw*.9*scale));expect(feet).toHaveLength(2);const gaps={};for(const foot of feet){const gap=floor.top-bounds(foot).bottom,side=foot.opacity===1?'front':'rear';gaps[side]=gap;expect(gap).toBeGreaterThanOrEqual(-.05);if(side==='front'||phase===0||phase===4||phase>=1&&phase<=3)expect(Math.abs(gap)).toBeLessThan(.05);if(side==='rear'&&phase>.05&&phase<.95)expect(gap).toBeGreaterThan(0);}
 measurements.push({body:bodyName,sample,phase,floorTopDp:floor.top,frontGapDp:gaps.front,rearGapDp:gaps.rear,maxCropExcessDp:maxCropExcess});return feet.find(s=>s.opacity===1);
}
beforeEach(()=>{jest.useFakeTimers();coordinator.resetPreviewPlayback();jest.spyOn(AccessibilityInfo,'isReduceMotionEnabled').mockResolvedValue(false);jest.spyOn(manifest,'resolveMovementPreview').mockImplementation(s=>fixtures.get(s?.movement_id)??null);});
afterEach(()=>{cleanup();jest.useRealTimers();jest.restoreAllMocks();coordinator.resetPreviewPlayback();});
test.each(Object.keys(DUAL_BODY_PARAMETERS))('52 full actual RN View cycle and terminal closure (%s)',async body=>{const e=fixtures.get(52),segs=e.frameData.segmentDurationsMs,total=segs.reduce((a,b)=>a+b,0);render(<MovementPreview movement={subject(52)} bodyType={body} reducedMotion={false} singleCycle={true}/>);await act(async()=>{});const first=drawing(),front=JSON.stringify(inspect(body,0,'initial'));noMotion();fireEvent.press(control());
 for(let t=0;t<=total+33;t+=33){const phase=poseAtTime(e.frames.map(f=>f.joints),Math.min(t,total),segs).rl;expect(JSON.stringify(inspect(body,phase,t))).toEqual(front);act(()=>jest.advanceTimersByTime(33));}expect(drawing()).toEqual(first);expect(control()).toHaveTextContent('REPLAY');expect(screen.getByTestId('movement-preview-position')).toHaveTextContent('Position 6 of 6');noMotion();act(()=>jest.advanceTimersByTime(30000));expect(drawing()).toEqual(first);
});
test.each(Object.keys(DUAL_BODY_PARAMETERS))('52 authored reduced-motion bounds, contact, captions and accessibility (%s)',async body=>{const e=fixtures.get(52);render(<MovementPreview movement={subject(52)} bodyType={body} reducedMotion={true}/>);await act(async()=>{});const first=drawing();for(let i=0;i<e.frames.length;i++){inspect(body,e.frames[i].joints.rl,'authored-'+i);expect(control().props.accessibilityRole).toBe('button');expect(control().props.accessibilityLabel).toBe('Show the next position of the '+e.name+' preview');expect(StyleSheet.flatten(control().props.style).minHeight).toBeGreaterThanOrEqual(theme.touch.min);expect(screen.getByTestId('movement-preview-caption')).toHaveTextContent(e.frames[i].caption);expect(screen.getByTestId('movement-preview-figure').props.accessibilityLabel).toContain(e.frames[i].caption);noMotion();fireEvent.press(control());}expect(drawing()).toEqual(first);noMotion();});
test.each(Object.keys(DUAL_BODY_PARAMETERS))('52 pause/resume/background/reduced-motion/identity/unmount (%s)',async body=>{let listener;const remove=jest.fn();jest.spyOn(AppState,'addEventListener').mockImplementation((type,fn)=>{listener=fn;return{remove};});const view=render(<MovementPreview movement={subject(52)} bodyType={body} reducedMotion={false}/>);await act(async()=>{});noMotion();fireEvent.press(control());act(()=>jest.advanceTimersByTime(264));const paused=drawing();fireEvent.press(control());expect(drawing()).toEqual(paused);noMotion();act(()=>jest.advanceTimersByTime(1000));expect(drawing()).toEqual(paused);fireEvent.press(control());act(()=>jest.advanceTimersByTime(33));expect(drawing()).not.toEqual(paused);const held=drawing();act(()=>listener('background'));expect(drawing()).toEqual(held);noMotion();act(()=>listener('active'));act(()=>jest.advanceTimersByTime(1000));expect(drawing()).toEqual(held);fireEvent.press(control());view.rerender(<MovementPreview movement={subject(52)} bodyType={body} reducedMotion={true}/>);noMotion();view.rerender(<MovementPreview movement={subject(53)} bodyType={body} reducedMotion={false}/>);expect(control()).toHaveTextContent('PLAY');expect(screen.getByTestId('movement-preview-position')).toHaveTextContent('Position 1 of 6');noMotion();fireEvent.press(control());view.rerender(<MovementPreview movement={{movement_id:99999}} bodyType={body} reducedMotion={false}/>);expect(screen.queryByTestId('movement-preview-control')).toBeNull();noMotion();view.unmount();expect(remove).toHaveBeenCalledTimes(1);});
test('52 real source remains pending and default global gate never opens',()=>{expect(raw.entries.find(e=>e.movementId===52).status).toBe('pending');jest.restoreAllMocks();expect(manifest.resolveMovementPreview(subject(52))).toBeNull();});
afterAll(()=>fs.writeFileSync(path.join(__dirname,process.env.AUDIT_PRIOR_GEOMETRY==='1'?'actual-rn-negative-results.json':'actual-rn-results.json'),JSON.stringify(measurements,null,2)+'\n'));
