-- Ratified WO-4 taxonomy corrections (generated by --taxonomy-corrections).
-- Additive, idempotent, and intentionally leaves movement.pattern untouched.

UPDATE movement_taxonomy SET category = 'accessory'
WHERE movement_id = (SELECT movement_id FROM movement WHERE name = 'Cable Rope Overhead Triceps Extension');
-- Prior shipped category: push.

UPDATE movement_taxonomy SET category = 'accessory'
WHERE movement_id = (SELECT movement_id FROM movement WHERE name = 'Triceps Pushdown');
-- Prior shipped category: push.
