-- =============================================================================
-- 032_capability_content.sql
-- Additive capability content migration (roles, families, prerequisite edges).
-- Generated by scripts/generate-capability-migration.mjs.
-- =============================================================================

-- Movement Role Eligibility
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'major' FROM movement WHERE name = 'Front Squat';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'major' FROM movement WHERE name = 'Barbell Row';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'major' FROM movement WHERE name = 'Power Clean';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'major' FROM movement WHERE name = 'Sumo Deadlift';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Farmer Carry';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Suitcase Carry';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Road Run';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'BJJ Sparring Round';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Pallof Press';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Dead Bug';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Plank';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Band External Rotation';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Cable Internal Rotation';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Face Pull';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Band Pull-Apart';
INSERT OR IGNORE INTO movement_role_eligibility (movement_id, role)
SELECT movement_id, 'conditional' FROM movement WHERE name = 'Kettlebell Turkish Get-Up';

-- Movement Capability Family
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'squat-competition', 0 FROM movement WHERE name = 'Bodyweight Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'squat-competition', 0 FROM movement WHERE name = 'Goblet Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'squat-competition', 0 FROM movement WHERE name = 'Front Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'squat-competition', 1 FROM movement WHERE name = 'Competition Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'hinge-deadlift', 0 FROM movement WHERE name = 'Glute Bridge';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'hinge-deadlift', 0 FROM movement WHERE name = 'Dumbbell Romanian Deadlift';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'hinge-deadlift', 0 FROM movement WHERE name = 'Romanian Deadlift';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'hinge-deadlift', 1 FROM movement WHERE name = 'Deadlift';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-bench', 0 FROM movement WHERE name = 'Incline Push-Up';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-bench', 0 FROM movement WHERE name = 'Dumbbell Floor Press';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-bench', 0 FROM movement WHERE name = 'Dumbbell Bench Press';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-bench', 1 FROM movement WHERE name = 'Competition Bench';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-overhead', 0 FROM movement WHERE name = 'Dumbbell Shoulder Press';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'press-overhead', 1 FROM movement WHERE name = 'Overhead Press';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'row-barbell', 0 FROM movement WHERE name = 'Chest-Supported Dumbbell Row';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'row-barbell', 0 FROM movement WHERE name = 'Single-Arm Dumbbell Row';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'row-barbell', 1 FROM movement WHERE name = 'Barbell Row';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'lunge-split', 0 FROM movement WHERE name = 'Dumbbell Reverse Lunge';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'lunge-split', 0 FROM movement WHERE name = 'Dumbbell Split Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'lunge-split', 1 FROM movement WHERE name = 'Bulgarian Split Squat';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'carry-loaded', 0 FROM movement WHERE name = 'Suitcase Carry';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'carry-loaded', 1 FROM movement WHERE name = 'Farmer Carry';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'core-antiextension', 0 FROM movement WHERE name = 'Dead Bug';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'core-antiextension', 0 FROM movement WHERE name = 'Plank';
INSERT OR IGNORE INTO movement_capability_family (movement_id, family, is_anchor)
SELECT movement_id, 'core-antiextension', 1 FROM movement WHERE name = 'Barbell Ab Rollout';

-- Movement Capability Edge
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Bodyweight Squat' AND m.name = 'Goblet Squat';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Goblet Squat' AND m.name = 'Front Squat';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 3, 3, 5, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Front Squat' AND m.name = 'Competition Squat';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Glute Bridge' AND m.name = 'Dumbbell Romanian Deadlift';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Romanian Deadlift' AND m.name = 'Romanian Deadlift';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 3, 3, 5, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Romanian Deadlift' AND m.name = 'Deadlift';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Incline Push-Up' AND m.name = 'Dumbbell Floor Press';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Floor Press' AND m.name = 'Dumbbell Bench Press';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 3, 3, 5, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Bench Press' AND m.name = 'Competition Bench';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 3, 3, 5, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Shoulder Press' AND m.name = 'Overhead Press';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Chest-Supported Dumbbell Row' AND m.name = 'Single-Arm Dumbbell Row';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 3, 3, 5, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Single-Arm Dumbbell Row' AND m.name = 'Barbell Row';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Reverse Lunge' AND m.name = 'Dumbbell Split Squat';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dumbbell Split Squat' AND m.name = 'Bulgarian Split Squat';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 45, 'time', NULL, 0
FROM movement p, movement m
WHERE p.name = 'Suitcase Carry' AND m.name = 'Farmer Carry';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 8, 'reps', 8.5, 0
FROM movement p, movement m
WHERE p.name = 'Dead Bug' AND m.name = 'Plank';
INSERT OR IGNORE INTO movement_capability_edge (
  prerequisite_movement_id, movement_id, relationship,
  min_sessions, min_sets_per_session, min_value, value_kind, max_rpe, requires_attestation
)
SELECT p.movement_id, m.movement_id, 'prerequisite', 2, 3, 45, 'time', NULL, 0
FROM movement p, movement m
WHERE p.name = 'Plank' AND m.name = 'Barbell Ab Rollout';

-- Expected Row-Count Assertions
SELECT CASE
  WHEN (SELECT COUNT(*) FROM movement_role_eligibility re JOIN movement m ON m.movement_id = re.movement_id WHERE m.name IN ('Front Squat', 'Barbell Row', 'Power Clean', 'Sumo Deadlift', 'Farmer Carry', 'Suitcase Carry', 'Road Run', 'BJJ Sparring Round', 'Pallof Press', 'Dead Bug', 'Plank', 'Band External Rotation', 'Cable Internal Rotation', 'Face Pull', 'Band Pull-Apart', 'Kettlebell Turkish Get-Up')) < 16
  THEN json('ASSERTION_FAILED_movement_role_eligibility_row_count_mismatch')
END;
SELECT CASE
  WHEN (SELECT COUNT(*) FROM movement_capability_family cf JOIN movement m ON m.movement_id = cf.movement_id WHERE m.name IN ('Bodyweight Squat', 'Goblet Squat', 'Front Squat', 'Competition Squat', 'Glute Bridge', 'Dumbbell Romanian Deadlift', 'Romanian Deadlift', 'Deadlift', 'Incline Push-Up', 'Dumbbell Floor Press', 'Dumbbell Bench Press', 'Competition Bench', 'Dumbbell Shoulder Press', 'Overhead Press', 'Chest-Supported Dumbbell Row', 'Single-Arm Dumbbell Row', 'Barbell Row', 'Dumbbell Reverse Lunge', 'Dumbbell Split Squat', 'Bulgarian Split Squat', 'Suitcase Carry', 'Farmer Carry', 'Dead Bug', 'Plank', 'Barbell Ab Rollout')) < 25
  THEN json('ASSERTION_FAILED_movement_capability_family_row_count_mismatch')
END;
SELECT CASE
  WHEN (SELECT COUNT(*) FROM movement_capability_edge ce
          JOIN movement pm ON pm.movement_id = ce.prerequisite_movement_id
          JOIN movement tm ON tm.movement_id = ce.movement_id
         WHERE (pm.name, tm.name) IN (VALUES ('Bodyweight Squat', 'Goblet Squat'), ('Goblet Squat', 'Front Squat'), ('Front Squat', 'Competition Squat'), ('Glute Bridge', 'Dumbbell Romanian Deadlift'), ('Dumbbell Romanian Deadlift', 'Romanian Deadlift'), ('Romanian Deadlift', 'Deadlift'), ('Incline Push-Up', 'Dumbbell Floor Press'), ('Dumbbell Floor Press', 'Dumbbell Bench Press'), ('Dumbbell Bench Press', 'Competition Bench'), ('Dumbbell Shoulder Press', 'Overhead Press'), ('Chest-Supported Dumbbell Row', 'Single-Arm Dumbbell Row'), ('Single-Arm Dumbbell Row', 'Barbell Row'), ('Dumbbell Reverse Lunge', 'Dumbbell Split Squat'), ('Dumbbell Split Squat', 'Bulgarian Split Squat'), ('Suitcase Carry', 'Farmer Carry'), ('Dead Bug', 'Plank'), ('Plank', 'Barbell Ab Rollout'))) < 17
  THEN json('ASSERTION_FAILED_movement_capability_edge_row_count_mismatch')
END;

-- Embedded Chain Projection Template
-- =============================================================================
-- _chain_projection.sql.tpl — SQL chain projection template.
-- Re-projects movement_progression (movement_id, progression_group, progression_rank)
-- from movement_capability_family and movement_capability_edge.
--
-- Atomically deletes and replaces movement_progression within a single transaction
-- to prevent transient UNIQUE index violations during chain reordering.
-- =============================================================================

DELETE FROM movement_progression;

INSERT INTO movement_progression (movement_id, progression_group, progression_rank)
WITH RECURSIVE
  valid_edges AS (
    SELECT
      e.prerequisite_movement_id AS src,
      e.movement_id AS dst,
      pf.family AS family
    FROM movement_capability_edge e
    JOIN movement_capability_family pf ON pf.movement_id = e.prerequisite_movement_id
    JOIN movement_capability_family mf ON mf.movement_id = e.movement_id
    WHERE e.relationship = 'prerequisite'
      AND pf.family = mf.family
  ),
  roots AS (
    SELECT
      f.movement_id AS root_id,
      f.family AS family
    FROM movement_capability_family f
    WHERE NOT EXISTS (
      SELECT 1 FROM valid_edges e WHERE e.dst = f.movement_id
    )
  ),
  chain_walk AS (
    SELECT
      r.root_id AS movement_id,
      r.family AS progression_group,
      0 AS progression_rank
    FROM roots r

    UNION ALL

    SELECT
      e.dst AS movement_id,
      w.progression_group,
      w.progression_rank + 1 AS progression_rank
    FROM chain_walk w
    JOIN valid_edges e ON e.src = w.movement_id AND e.family = w.progression_group
  )
SELECT movement_id, progression_group, progression_rank
FROM chain_walk
ORDER BY progression_group ASC, progression_rank ASC;
