-- Phase 2a: stable media identity, separate from coaching copy and URI storage.
-- Existing fallback URLs remain frozen in movement_detail.video_placeholder_uri.
CREATE TABLE IF NOT EXISTS movement_media (
  movement_id INTEGER PRIMARY KEY REFERENCES movement ON DELETE CASCADE,
  asset_key   TEXT NOT NULL UNIQUE,
  status      TEXT NOT NULL CHECK (status IN ('planned', 'external_fallback', 'ready')),
  revision    INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

INSERT INTO movement_media (movement_id, asset_key, status, revision)
SELECT m.movement_id, e.column2, 'external_fallback', 1
FROM (VALUES
  ('Arnold Press', 'movement/arnold-press/demo/v1'),
  ('Band External Rotation', 'movement/band-external-rotation/demo/v1'),
  ('Band Good Morning', 'movement/band-good-morning/demo/v1'),
  ('Band Pull-Apart', 'movement/band-pull-apart/demo/v1'),
  ('Band Row', 'movement/band-row/demo/v1'),
  ('Barbell Ab Rollout', 'movement/barbell-ab-rollout/demo/v1'),
  ('Barbell Curl', 'movement/barbell-curl/demo/v1'),
  ('Barbell Hack Squat', 'movement/barbell-hack-squat/demo/v1'),
  ('Barbell Hip Thrust', 'movement/barbell-hip-thrust/demo/v1'),
  ('Barbell Rear Delt Row', 'movement/barbell-rear-delt-row/demo/v1'),
  ('Barbell Row', 'movement/barbell-row/demo/v1'),
  ('Barbell Seated Calf Raise', 'movement/barbell-seated-calf-raise/demo/v1'),
  ('Barbell Shrug', 'movement/barbell-shrug/demo/v1'),
  ('Barbell Step-Up', 'movement/barbell-step-up/demo/v1'),
  ('Bench Dip', 'movement/bench-dip/demo/v1'),
  ('Bent Press', 'movement/bent-press/demo/v1'),
  ('BJJ Sparring Round', 'movement/bjj-sparring-round/demo/v1'),
  ('Bodyweight Squat', 'movement/bodyweight-squat/demo/v1'),
  ('Box Squat', 'movement/box-squat/demo/v1'),
  ('Bulgarian Split Squat', 'movement/bulgarian-split-squat/demo/v1'),
  ('Cable Chest Press', 'movement/cable-chest-press/demo/v1'),
  ('Cable Crunch', 'movement/cable-crunch/demo/v1'),
  ('Cable Deadlifts', 'movement/cable-deadlifts/demo/v1'),
  ('Cable Glute Kickback', 'movement/cable-glute-kickback/demo/v1'),
  ('Cable Hammer Curls - Rope Attachment', 'movement/cable-hammer-curls-rope-attachment/demo/v1'),
  ('Cable Internal Rotation', 'movement/cable-internal-rotation/demo/v1'),
  ('Cable Pull-Through', 'movement/cable-pull-through/demo/v1'),
  ('Cable Reverse Crunch', 'movement/cable-reverse-crunch/demo/v1'),
  ('Cable Rope Overhead Triceps Extension', 'movement/cable-rope-overhead-triceps-extension/demo/v1'),
  ('Cable Rope Rear-Delt Rows', 'movement/cable-rope-rear-delt-rows/demo/v1'),
  ('Cable Row', 'movement/cable-row/demo/v1'),
  ('Cable Shoulder Press', 'movement/cable-shoulder-press/demo/v1'),
  ('Calf Raises - With Bands', 'movement/calf-raises-with-bands/demo/v1'),
  ('Chest-Supported Dumbbell Row', 'movement/chest-supported-dumbbell-row/demo/v1'),
  ('Chin-up', 'movement/chin-up/demo/v1'),
  ('Close-Grip Bench Press', 'movement/close-grip-bench-press/demo/v1'),
  ('Close-Grip Dumbbell Press', 'movement/close-grip-dumbbell-press/demo/v1'),
  ('Competition Bench', 'movement/competition-bench/demo/v1'),
  ('Competition Squat', 'movement/competition-squat/demo/v1'),
  ('Cuban Press', 'movement/cuban-press/demo/v1'),
  ('Dead Bug', 'movement/dead-bug/demo/v1'),
  ('Deadlift', 'movement/deadlift/demo/v1'),
  ('Decline Bench Press', 'movement/decline-bench-press/demo/v1'),
  ('Decline Crunch', 'movement/decline-crunch/demo/v1'),
  ('Decline Dumbbell Bench Press', 'movement/decline-dumbbell-bench-press/demo/v1'),
  ('Deficit Deadlift', 'movement/deficit-deadlift/demo/v1'),
  ('Dip', 'movement/dip/demo/v1'),
  ('Double Kettlebell Front Squat', 'movement/double-kettlebell-front-squat/demo/v1'),
  ('Double Kettlebell Push Press', 'movement/double-kettlebell-push-press/demo/v1'),
  ('Dumbbell Bench Press', 'movement/dumbbell-bench-press/demo/v1'),
  ('Dumbbell Floor Press', 'movement/dumbbell-floor-press/demo/v1'),
  ('Dumbbell Flye', 'movement/dumbbell-flye/demo/v1'),
  ('Dumbbell Front Raise', 'movement/dumbbell-front-raise/demo/v1'),
  ('Dumbbell Lateral Raise', 'movement/dumbbell-lateral-raise/demo/v1'),
  ('Dumbbell Lunge', 'movement/dumbbell-lunge/demo/v1'),
  ('Dumbbell Reverse Lunge', 'movement/dumbbell-reverse-lunge/demo/v1'),
  ('Dumbbell Romanian Deadlift', 'movement/dumbbell-romanian-deadlift/demo/v1'),
  ('Dumbbell Shoulder Press', 'movement/dumbbell-shoulder-press/demo/v1'),
  ('Dumbbell Shrug', 'movement/dumbbell-shrug/demo/v1'),
  ('Dumbbell Split Squat', 'movement/dumbbell-split-squat/demo/v1'),
  ('Dumbbell Squat', 'movement/dumbbell-squat/demo/v1'),
  ('Dumbbell Step-Up', 'movement/dumbbell-step-up/demo/v1'),
  ('Dumbbell Sumo Squat', 'movement/dumbbell-sumo-squat/demo/v1'),
  ('Eccentric Wall Handstand Push-Up', 'movement/eccentric-wall-handstand-push-up/demo/v1'),
  ('Face Pull', 'movement/face-pull/demo/v1'),
  ('Farmer Carry', 'movement/farmer-carry/demo/v1'),
  ('Feet-Elevated Push-Up', 'movement/feet-elevated-push-up/demo/v1'),
  ('Floor Back Extension', 'movement/floor-back-extension/demo/v1'),
  ('Front Squat', 'movement/front-squat/demo/v1'),
  ('Glute Bridge', 'movement/glute-bridge/demo/v1'),
  ('Goblet Squat', 'movement/goblet-squat/demo/v1'),
  ('Good Morning', 'movement/good-morning/demo/v1'),
  ('Hammer Curl', 'movement/hammer-curl/demo/v1'),
  ('Handstand Push-Up', 'movement/handstand-push-up/demo/v1'),
  ('Hanging Leg Raise', 'movement/hanging-leg-raise/demo/v1'),
  ('Incline Dumbbell Press', 'movement/incline-dumbbell-press/demo/v1'),
  ('Incline Push-Up', 'movement/incline-push-up/demo/v1'),
  ('Inverted Row', 'movement/inverted-row/demo/v1'),
  ('Jefferson Squats', 'movement/jefferson-squats/demo/v1'),
  ('Kettlebell Dead Clean', 'movement/kettlebell-dead-clean/demo/v1'),
  ('Kettlebell Pistol Squat', 'movement/kettlebell-pistol-squat/demo/v1'),
  ('Kettlebell Swing', 'movement/kettlebell-swing/demo/v1'),
  ('Kettlebell Turkish Get-Up', 'movement/kettlebell-turkish-get-up/demo/v1'),
  ('Kneeling Single-Arm High Pulley Row', 'movement/kneeling-single-arm-high-pulley-row/demo/v1'),
  ('Lat Pulldown', 'movement/lat-pulldown/demo/v1'),
  ('Lying Dumbbell Triceps Extension', 'movement/lying-dumbbell-triceps-extension/demo/v1'),
  ('Narrow Stance Squats', 'movement/narrow-stance-squats/demo/v1'),
  ('Nordic Curl', 'movement/nordic-curl/demo/v1'),
  ('One Arm Lat Pulldown', 'movement/one-arm-lat-pulldown/demo/v1'),
  ('One-Arm Kettlebell Row', 'movement/one-arm-kettlebell-row/demo/v1'),
  ('One-Arm Overhead Kettlebell Squat', 'movement/one-arm-overhead-kettlebell-squat/demo/v1'),
  ('Overhead Press', 'movement/overhead-press/demo/v1'),
  ('Pallof Press', 'movement/pallof-press/demo/v1'),
  ('Pike Push-Up', 'movement/pike-push-up/demo/v1'),
  ('Plank', 'movement/plank/demo/v1'),
  ('Power Clean', 'movement/power-clean/demo/v1'),
  ('Preacher Curl', 'movement/preacher-curl/demo/v1'),
  ('Pull-Up', 'movement/pull-up/demo/v1'),
  ('Push-up', 'movement/push-up/demo/v1'),
  ('Renegade Row', 'movement/renegade-row/demo/v1'),
  ('Reverse Barbell Curl', 'movement/reverse-barbell-curl/demo/v1'),
  ('Reverse Crunch', 'movement/reverse-crunch/demo/v1'),
  ('Reverse Grip Bent-Over Rows', 'movement/reverse-grip-bent-over-rows/demo/v1'),
  ('Road Run', 'movement/road-run/demo/v1'),
  ('Romanian Deadlift', 'movement/romanian-deadlift/demo/v1'),
  ('Russian Twist', 'movement/russian-twist/demo/v1'),
  ('Scapular Pull-Up', 'movement/scapular-pull-up/demo/v1'),
  ('Single-Arm Dumbbell Row', 'movement/single-arm-dumbbell-row/demo/v1'),
  ('Single-Leg Glute Bridge', 'movement/single-leg-glute-bridge/demo/v1'),
  ('Single-Leg Romanian Deadlift', 'movement/single-leg-romanian-deadlift/demo/v1'),
  ('Sit-Up', 'movement/sit-up/demo/v1'),
  ('Standing Barbell Calf Raise', 'movement/standing-barbell-calf-raise/demo/v1'),
  ('Standing Dumbbell Calf Raise', 'movement/standing-dumbbell-calf-raise/demo/v1'),
  ('Straight-Arm Pulldown', 'movement/straight-arm-pulldown/demo/v1'),
  ('Suitcase Carry', 'movement/suitcase-carry/demo/v1'),
  ('Sumo Deadlift', 'movement/sumo-deadlift/demo/v1'),
  ('T-Bar Row', 'movement/t-bar-row/demo/v1'),
  ('Triceps Pushdown', 'movement/triceps-pushdown/demo/v1'),
  ('Tuck Crunch', 'movement/tuck-crunch/demo/v1'),
  ('V-Bar Pulldown', 'movement/v-bar-pulldown/demo/v1'),
  ('Walking Lunge', 'movement/walking-lunge/demo/v1'),
  ('Weighted Pull-up', 'movement/weighted-pull-up/demo/v1'),
  ('Zercher Squat', 'movement/zercher-squat/demo/v1'),
  ('Zottman Curl', 'movement/zottman-curl/demo/v1')
) AS e
JOIN movement AS m ON m.name = e.column1
ON CONFLICT(movement_id) DO UPDATE SET
  asset_key = excluded.asset_key,
  status = 'external_fallback',
  revision = 1;
