import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import ts from 'typescript';
import { primToSvg, ROLE_HEX } from '../../../tools/rendering/lib/canonicalSvg.mjs';
const ROOT=process.cwd(),OUT=path.resolve('acceptance-evidence/dot/technique-audit'),P='apps/mobile/src/components/movementPreview';
const HEAD='cad9de98fe9173a7533c294f7a62fd6ba9ea35b7',PREVIOUS='1185f0d0d6eb91b482afe60af4a0bf8173ba8c06',V7='510127dd54798ad7963139908a2207e73531d119';
const IDS=[143,53,82,138,163,92,158,253,80,262,292,264,49,178,220,84];
const sha=b=>createHash('sha256').update(b).digest('hex');
const git=(...a)=>execFileSync('git',a,{cwd:ROOT,env:{...process.env,GIT_OPTIONAL_LOCKS:'0'},encoding:'utf8',maxBuffer:16*1024*1024}).trim();
const blob=(rev,p)=>execFileSync('git',['show',`${rev}:${p}`],{cwd:ROOT,env:{...process.env,GIT_OPTIONAL_LOCKS:'0'},maxBuffer:16*1024*1024});
const expect=(ok,msg)=>{if(!ok)throw Error(msg);};
expect(git('rev-parse','HEAD')===HEAD,'Head changed');
expect(!git('status','--porcelain','--',P,'tools/rendering'),'Product changed');
function evaluate(source,name,figure){const exports={},module={exports};new Function('exports','require','module',ts.transpileModule(source,{fileName:name,compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,strict:true}}).outputText)(exports,id=>{if(id==='./canonicalFigure')return figure;throw Error(`Unexpected require ${id}`);},module);return module.exports;}
function load(rev){const figure=evaluate(blob(rev,`${P}/canonicalFigure.ts`).toString(),'canonicalFigure.ts');const derivation=evaluate(blob(rev,`${P}/derivation.ts`).toString(),'derivation.ts',figure);const files=git('ls-tree','-r','--name-only',rev,'--',`${P}/families`).split(/\r?\n/).filter(x=>x.endsWith('.json'));const raw=files.flatMap(p=>JSON.parse(blob(rev,p)).entries);const entries=raw.map(e=>derivation.isVariantEntry(e)?derivation.deriveVariantEntry(e,raw.find(b=>b.movementId===e.derivesFrom)):e);return{rev,figure,entries,files};}
const candidate=load(HEAD),before=load(PREVIOUS),baselines=[before];
try{git('cat-file','-e',`${V7}^{commit}`);baselines.push(load(V7));}catch{console.log('V7 source object unavailable; direct V8 comparison still runs');}
const sourcePaths=[...candidate.files,`${P}/previewIndex.json`,`${P}/canonicalFigure.ts`,`${P}/derivation.ts`,`${P}/MovementPreview.tsx`,'tools/rendering/lib/canonicalSvg.mjs','tools/rendering/render_motion_cycle.mjs','tools/rendering/render_movement_evidence.mjs','packages/core-db/src/schema/025_movement_coaching_content.sql','docs/audits/accessible-coach/movement-completion/REVERSE_LUNGE_SOURCE_BINDING.json'];
const sources=sourcePaths.map(p=>({path:p,gitSha256:sha(blob(HEAD,p)),diskSha256:sha(fs.readFileSync(p))}));expect(sources.every(s=>s.gitSha256===s.diskSha256),'Disk differs from committed inputs');
const ticks=(f,e)=>{const total=f.segmentDurations(e.frames.length,e.segmentDurationsMs).reduce((a,b)=>a+b,0);return[...Array.from({length:Math.ceil(total/33)},(_,i)=>i*33),total];};
const frames=(s,id,bodyName)=>{const e=s.entries.find(e=>e.movementId===id),f=s.figure,body=f.DUAL_BODY_PARAMETERS[bodyName];return ticks(f,e).map(t=>{const pose=f.poseAtTime(e.frames.map(f=>f.joints),t,e.segmentDurationsMs),opts={...e,body,implementTiltWeight:f.peakWeightAtTime(e.frames,e.frameRoles,t,e.segmentDurationsMs)};return{time:t,joints:f.resolveFigureJoints(pose,opts),primitives:f.layoutCanonicalFigure(pose,opts)};});};
const preservation=[];
for(const base of baselines){const cycles=[];for(const id of IDS)for(const body of Object.keys(candidate.figure.DUAL_BODY_PARAMETERS)){const now=frames(candidate,id,body),then=frames(base,id,body),entryIdentical=JSON.stringify(candidate.entries.find(e=>e.movementId===id))===JSON.stringify(base.entries.find(e=>e.movementId===id));const joints=now.map(f=>f.joints),prims=now.map(f=>f.primitives);const resolvedJointsIdentical=JSON.stringify(joints)===JSON.stringify(then.map(f=>f.joints)),completePrimitivesIdentical=JSON.stringify(prims)===JSON.stringify(then.map(f=>f.primitives));expect(entryIdentical&&resolvedJointsIdentical&&completePrimitivesIdentical,`Changed ${id}/${body} vs ${base.rev}`);cycles.push({id,body,tickCount:now.length,totalMs:now.at(-1).time,entryIdentical,resolvedJointsIdentical,completePrimitivesIdentical,resolvedJointsSha256:sha(JSON.stringify(joints)),completePrimitivesSha256:sha(JSON.stringify(prims))});}preservation.push({baselineCommit:base.rev,bodyCycleCount:cycles.length,poseCount:cycles.reduce((n,c)=>n+c.tickCount,0),cycles});}
const f=candidate.figure,e=candidate.entries.find(e=>e.movementId===52),floor=96.9,dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function bottom(p){const dx=p.x2-p.x1,dy=p.y2-p.y1,L=Math.hypot(dx,dy),r=p.w/2;return(p.y1+p.y2)/2+(L/2-r)*Math.abs(dy/L)+r;}
const repair=[];
for(const [bodyName,body]of Object.entries(f.DUAL_BODY_PARAMETERS)){const start=f.reverseLungeGeometry(0,body),samples=[];for(const time of ticks(f,e)){const pose=f.poseAtTime(e.frames.map(x=>x.joints),time,e.segmentDurationsMs),g=f.reverseLungeGeometry(pose.rl,body),j=f.resolveFigureJoints(pose,{...e,body}),p=f.layoutCanonicalFigure(pose,{...e,body}),foot=g.rearFoot,front=g.frontFoot;const rear=p.find(x=>x.kind==='bone'&&x.w===g.footWidth&&x.x1===foot[0][0]&&x.y1===foot[0][1]&&x.x2===foot[1][0]&&x.y2===foot[1][1]);const planted=p.find(x=>x.kind==='bone'&&x.w===g.footWidth&&x.x1===front[0][0]&&x.y1===front[0][1]&&x.x2===front[1][0]&&x.y2===front[1][1]);expect(rear&&planted,'Exact production foot primitives absent');const rearGap=floor-bottom(rear),frontGap=floor-bottom(planted),kneeGap=floor-j.kf[1]-body.lw*1.18/2;const legError=Math.max(...[[j.nLeg,j.kn,j.an],[j.fLeg,j.kf,j.af]].flatMap(([r,k,a])=>[Math.abs(dist(r,k)-22.25),Math.abs(dist(k,a)-22.25)]));const armError=Math.max(...[[j.nArm,j.el,j.wr],[j.fArm,j.ef,j.wf]].flatMap(([r,k,a])=>[Math.abs(dist(r,k)-12.5),Math.abs(dist(k,a)-12)]));const shafts=p.filter(x=>x.kind==='bone'&&x.w===2.2);expect(shafts.length===2,'Dumbbell shaft count');const near=shafts.find(x=>x.color==='textHi'),far=shafts.find(x=>x.color==='textLow');const shaftError=Math.max(dist([(near.x1+near.x2)/2,(near.y1+near.y2)/2],j.wr),dist([(far.x1+far.x2)/2,(far.y1+far.y2)/2],j.wf));expect(JSON.stringify(front)===JSON.stringify(start.frontFoot),'Front moved');expect(Math.abs(frontGap)<1e-9&&rearGap>=-1e-9,'Floor bounds');expect(pose.rl<1||pose.rl>3||Math.abs(rearGap)<1e-9,'Support gap');expect(legError<1e-9&&armError<1e-9&&shaftError<1e-9,'Length or load attachment drift');expect(kneeGap>0,'Knee floor contact');expect(j.hp[1]-j.nk[1]===24&&j.hp[0]===j.nk[0]&&j.nk[1]-j.hd[1]===9,'Trunk/head drift');samples.push({timeMs:time,phase:pose.rl,rearPaintedGapCanonical:rearGap,rearPaintedGapApp240Dp:rearGap*2.5,frontPaintedGapCanonical:frontGap,rearKneeConservativeEnvelopeGapCanonical:kneeGap,legLengthMaxError:legError,armLengthMaxError:armError,dumbbellCenterMaxError:shaftError,rearFootLength:dist(...foot)});}
const outFrames=frames(candidate,52,bodyName);expect(JSON.stringify(outFrames[0].joints)===JSON.stringify(outFrames.at(-1).joints),'Joint loop does not close');expect(JSON.stringify(outFrames[0].primitives)===JSON.stringify(outFrames.at(-1).primitives),'Primitive loop does not close');const support=samples.filter(x=>x.phase>=1&&x.phase<=3);const old=before.figure.reverseLungeGeometry(2,body),oldp={x1:old.rearFoot[0][0],y1:old.rearFoot[0][1],x2:old.rearFoot[1][0],y2:old.rearFoot[1][1],w:old.footWidth};expect(floor-bottom(oldp)>1,'Negative control not reproduced');repair.push({body:bodyName,tickCount:samples.length,totalMs:samples.at(-1).timeMs,supportedSampleCount:support.length,maxAbsoluteSupportedGapCanonical:Math.max(...support.map(x=>Math.abs(x.rearPaintedGapCanonical))),old1185SupportedGapCanonical:floor-bottom(oldp),old1185SupportedGapApp240Dp:(floor-bottom(oldp))*2.5,minRearKneeConservativeEnvelopeGapCanonical:Math.min(...samples.map(x=>x.rearKneeConservativeEnvelopeGapCanonical)),minRearKneeConservativeEnvelopeGapApp240Dp:Math.min(...samples.map(x=>x.rearKneeConservativeEnvelopeGapCanonical))*2.5,maxLegLengthError:Math.max(...samples.map(x=>x.legLengthMaxError)),maxArmLengthError:Math.max(...samples.map(x=>x.armLengthMaxError)),maxDumbbellCenterError:Math.max(...samples.map(x=>x.dumbbellCenterMaxError)),jointLoopClosed:true,completePrimitiveLoopClosed:true,samples});}
const cycleDir='acceptance-evidence/dot/recheck52-cycles',ci=JSON.parse(fs.readFileSync(`${cycleDir}/cycle_evidence.json`));expect(ci.sourceCommit===HEAD&&ci.sourcesCommittedAtRender,'Cycle binding');const artifact=[];for(const[p,h]of Object.entries(ci.sourceHashes))expect(sha(fs.readFileSync(p))===h&&sha(blob(HEAD,p))===h,`Cycle source ${p}`);for(const move of ci.movements)for(const r of move.records){const pp=`${cycleDir}/movement-${move.id}/${r.body}-cycle.png`,hp=`${cycleDir}/movement-${move.id}/${r.body}-cycle.html`;expect(sha(fs.readFileSync(pp))===r.sheetSha256,'PNG hash');const html=fs.readFileSync(hp,'utf8');expect(sha(html)===r.htmlSha256,'HTML hash');const m=html.match(/const frames=(.*),times=(.*),stage=document/);expect(m,'Encoded arrays absent');const encoded=JSON.parse(m[1]),times=JSON.parse(m[2]),entry=candidate.entries.find(e=>e.movementId===move.id),[x,y,w,h]=entry.viewBox,scale=Math.min(240/w,240/h),width=Math.ceil(w*scale),height=Math.ceil(h*scale);const expected=frames(candidate,move.id,r.body).map(frame=>`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" fill="${ROLE_HEX.ink1}"/>${frame.primitives.map(p=>primToSvg(p,[x,y,w,h],scale)).join('')}</svg>`);expect(JSON.stringify(encoded)===JSON.stringify(expected)&&sha(JSON.stringify(encoded))===r.primitiveFramesSha256,'Encoded primitive drift');expect(JSON.stringify(times)===JSON.stringify(ticks(f,entry)),'Timeline drift');artifact.push({id:move.id,body:r.body,png:pp,pngSha256:r.sheetSha256,html:hp,htmlSha256:r.htmlSha256,primitiveFramesSha256:r.primitiveFramesSha256,tickCount:r.tickCount});}
const cards=JSON.parse(fs.readFileSync('acceptance-evidence/dot/recheck52-cards/evidence_index.json'));expect(cards.sourceCommit===HEAD&&cards.sourcesCommittedAtRender,'Card binding');const cardArtifacts=[];for(const c of cards.cards)for(const kind of ['svg','png']){const p=c[`${kind}Path`],h=c[`${kind}Sha256`];expect(sha(fs.readFileSync(p))===h,'Card artifact hash');cardArtifacts.push({path:p,sha256:h});}
const report={verdict:'INCOMPLETE',boundedContactFinding:'V8-1 finite rounded-foot gap repaired in all sampled production poses; qualified/native/supplemental alignment acceptance remains pending.',candidate:{worktree:ROOT,branch:git('branch','--show-current'),head:HEAD,tree:git('rev-parse','HEAD^{tree}'),status:git('status','--porcelain')},sourceHashes:sources,preservation,repair,entry52:{status:e.status,view:e.view,segmentDurationsMs:e.segmentDurationsMs,captions:e.frames.map(x=>x.caption)},freshCycleArtifactVerification:{bodyCycleCount:artifact.length,poseCount:artifact.reduce((n,c)=>n+c.tickCount,0),cycleEvidenceSha256:sha(fs.readFileSync(`${cycleDir}/cycle_evidence.json`)),artifacts:artifact},freshCardArtifactVerification:{cardCount:cards.cards.length,evidenceIndexSha256:sha(fs.readFileSync('acceptance-evidence/dot/recheck52-cards/evidence_index.json')),artifacts:cardArtifacts},limits:['No ordinary-speed browser or native playback observed in this probe','No Android/iOS device frame timing, accessibility or pixels observed','Side view does not prove frontal knee/pelvic alignment; no supplemental front alignment evidence','No qualified human technique certification; all previews must remain pending'],nativeApproval:false,techniqueApproval:false};
expect(git('rev-parse','HEAD')===HEAD&&!git('status','--porcelain','--',P,'tools/rendering'),'Source changed during review');
fs.writeFileSync(path.join(OUT,'initial-technique-evidence.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({candidate:report.candidate,preservation:preservation.map(x=>({baseline:x.baselineCommit,cycles:x.bodyCycleCount,poses:x.poseCount})),repair:repair.map(({samples,...x})=>x),verifiedCycleCount:artifact.length,verifiedPoseCount:artifact.reduce((n,c)=>n+c.tickCount,0),verifiedCardCount:cards.cards.length},null,2));
