export {
  AdjustmentValidationError,
  clampAdjustment,
  CUE_MAX_CHARS,
  CUE_MIN_CHARS,
  CUE_RE,
  LOAD_MODIFIER_LITERALS,
  NEUTRAL_ADJUSTMENT,
  RPE_CAP_LITERALS,
  SET_MODIFIER_FLOOR,
  SET_MODIFIER_LITERALS,
  validateAdjustment,
  type AdjustmentVector,
} from './outputSchema';
export {
  DEFAULT_PROFILE,
  DIFFICULTY_RANK,
  DIFFICULTY_RATINGS,
  ENERGY_SYSTEMS,
  EQUIPMENT_ITEMS,
  EQUIPMENT_PRESETS,
  STANDARD_EQUIPMENT_ITEMS,
  SPECIALIST_EQUIPMENT_ITEMS,
  EXPERIENCE_SEVERITY,
  MOVEMENT_PATTERNS,
  MOVEMENT_PREFERENCE,
  MOVEMENT_PREFIXES,
  OBJECTIVES,
  BIG4_LIFTS,
  MACRO_PHASES,
  PATTERN_TO_CATEGORY,
  PREFIX_TO_IMPLEMENT,
  PROGRESSION_METHODS,
  SCHEMA_TYPES,
  SELECTABLE_SCHEMA_TYPES,
  TAXONOMY_CATEGORIES,
  TAXONOMY_IMPLEMENTS,
  TRAINING_AGES,
  type BodyNote,
  type DifficultyRating,
  type EnergySystem,
  type EquipmentItem,
  type MovementPattern,
  type MovementPrefix,
  type MovementPrefixCondition,
  type MovementPreference,
  type Objective,
  type MacroPhase,
  type ProgressionMethod,
  type SchemaType,
  type SelectableSchemaType,
  type StateVectorRow,
  type TaxonomyCategory,
  type TaxonomyImplement,
  type TrainingAge,
  type UserProfile,
} from './types';
export { evaluatePolicy } from './policyReference';
export {
  effectiveMovementAccessContext,
  isDifficultyAllowed,
  type ExecutableMovementAccessContext,
  type MovementAccessContext,
} from './tierPolicy';
export {
  defaultLoadPreference,
  resolveLoadSelection,
  transitionLoadPreference,
  type AdvisoryKind,
  type LoadPreference,
  type LoadSelection,
  type LoadSelectionInput,
  type LoadSource,
} from './loadSelection';
export {
  derivePrescription,
  type DeriveInput,
  type DerivedPrescription,
  type ReportInput,
} from './derivePrescription';
export {
  defaultProgramDayIndices,
  addDaysIso,
  accessContextForBlockFocus,
  availableMovements,
  BLOCK_WEEKS,
  generateBlock,
  HYBRID_TAX_THRESHOLD,
  MACRO_BLOCKS,
  MACRO_TOTAL_WEEKS,
  programFocuses,
  programMacroIndex,
  macroPhaseOf,
  SCHEMA_FATIGUE_COST,
  splitExplainer,
  SPLIT_EXPLAINER_FOOTER,
  BLOCK_FOCI,
  BLOCK_FOCUS_LIST,
  targetLoadKg,
  targetPct,
  type BlockFocus,
  type BlockInput,
  type BlockPhase,
  type BlockPlan,
  type GeneratorMovement,
  type PlannedSessionPlan,
  type ProgramDayPreference,
  type ProgramMovementPreference,
  type PlannedSlotPlan,
} from './blockGenerator';
export {
  calculateEffectiveLoad,
  conditionApplies,
  NEUTRAL_PREFIX_MODIFIER,
  type EffectiveLoad,
} from './conditionEngine';
export {
  CONTROL_AUTHORITY,
  deriveControlAction,
  deriveDailyAdjustment,
  detectFlaws,
  FLAW_DETECTION_CONSTANTS,
  NEUTRAL_LOAD_MODIFIER,
  snapToLiteral,
  type ControlAction,
  type FlawClass,
  type FlawReport,
  type PatternCorrection,
  type PatternDailyDelta,
  type PatternFlaw,
} from './kinematicAutopilot';
export {
  buildPatternWindow,
  type WindowNiggleRow,
  type WindowSetRow,
} from './autopilotProjection';
export {
  buildCompletionWindow,
  composeControlActions,
  deriveCompletionAction,
  loggedCompletionShortfall,
  summarizeCompletionWindow,
  type CompletionActionPolicy,
  type CompletionPatternSummary,
  type PatternDailyCompletion,
  type WindowCompletionRow,
} from './completionAction';
export {
  applyProfileLimits,
  applySeverityToGuardrail,
  EXPERIENCE_TRIAGE,
  scaleGuardrailForExperience,
  type ProfileContext,
  type ProfileLimitedPrescription,
} from './profileLimits';
export {
  computeSubstitutions,
  DEFAULT_ACCESSORY_RATIO,
  JOINTS,
  NIGGLE_MAX,
  NIGGLE_MIN,
  PATTERN_JOINTS,
  SUBSTITUTION_COLORS,
  type DaySwapOption,
  type FutureSlot,
  type Joint,
  type NiggleInput,
  type RegressionOption,
  type SubstitutionInput,
  type SubstitutionLayer,
  type SubstitutionMovement,
  type SubstitutionResult,
  type TriageCluster,
  type TriageClusterMember,
} from './substitution';
export {
  RED_FLAG_PAIN,
  RED_FLAG_SYSTEMIC,
  resolveReport,
  scanRedFlags,
  type RedFlagScan,
  type ResolvedReport,
} from './semantic/redFlag';
export { getPrescription, type AdjustmentSource, type Prescription } from './prescribe';
export { normalize, packVectors, topK, type Match } from './semantic/cosine';
export {
  flattenTexts,
  isNoOpGuardrail,
  loadCodebase,
  type Guardrail,
  type LoadedCodebase,
  type PhraseCodebase,
  type PhraseEntry,
} from './semantic/codebase';
export { type Embedder } from './semantic/embedder';
export { WordPieceTokenizer, type TokenizerSpec } from './semantic/wordpiece';
export {
  createMiniLmEmbedder,
  type MiniLmEmbedderOptions,
  type OrtSessionLike,
  type OrtTensorCtor,
} from './semantic/onnxEmbedder';
export {
  AMBIGUITY_MARGIN,
  CONFIDENCE_THRESHOLD,
  applyGuardrail,
  moreConservative,
  triage,
  type SessionDirective,
  type TriageResult,
} from './semantic/triage';

// P16 progression ladders + P17 S1 session runner (engine-side; UI lands P17).
export {
  CAPABILITY_EVIDENCE_WINDOW_DAYS,
  DEFAULT_ADVANCEMENT_POLICY,
  resolveActiveRung,
  type AdvancementPolicy,
  type ProgressionRung,
  type RungResolution,
  type SessionSets,
} from './progressionEngine';
export {
  capabilityEdgeKey,
  resolveMovementAvailability,
  type CapabilityEdge,
  type CapabilityEvidence,
  type CapabilityMovement,
  type CapabilitySource,
  type MovementAvailability,
  type MovementAvailabilityState,
  type ResolveMovementAvailabilityInput,
} from './capabilityResolver';
export {
  HISTORY_FORMAT_VERSION,
  HISTORY_IMPORT_AI_PROMPT,
  HISTORY_IMPORT_EXAMPLE,
  historyContentFingerprint,
  parseHistoryImport,
  type HistoryMovementRef,
  type HistoryParseIssue,
  type HistoryParseResult,
  type ParsedHistorySession,
  type ParsedHistorySet,
} from './historyImport';
export {
  composeRoutine,
  groupRoutineTemplateDays,
  isRoutineRoleSnapshotExecutable,
  projectRoutineMajorRpe,
  rankRoutineSupplementaryRecommendations,
  routineMajorRpeForWeek,
  ROUTINE_TEMPLATE_MAX_DAYS,
  type ComposeRoutineInput,
  type ComposedRoutine,
  type RoutineTemplateSlotPlacement,
  type RoutineRoleEligibility,
  type RoutineRoleSnapshotRow,
  type RoutinePrescription,
  type RoutineMajorRpeProjection,
  type RoutineRecommendationMovement,
  type RoutineRole,
  type RoutineSelection,
  type RoutineSupplementaryRecommendation,
} from './routineComposer';
export {
  ROUTINE_FAMILY_STRESS_BUDGETS,
  composeRoutineMicrocycle,
  contextualRoutineRoles,
  rankRoutineAccessoryRecommendations,
  type ComposeRoutineMicrocycleInput,
  type ComposedRoutineMicrocycle,
  type RoutineAccessoryRecommendation,
  type RoutineAssistanceContract,
  type RoutineFamilyStressDecision,
  type RoutineLiftFamilyContract,
  type RoutineLegacyRoleAllowance,
  type RoutineMicrocycleMovement,
  type RoutineMicrocyclePrescription,
  type RoutineMicrocycleSelection,
  type RoutineSessionFamilyStress,
  type RoutineStressPurpose,
} from './routineMicrocycle';
export {
  RUNNER_CHECKPOINT_VERSION,
  RunnerCheckpointError,
  advance,
  createRunnerCheckpoint,
  currentSet,
  currentSlot,
  deserializeRunner,
  nextUp,
  replayRunner,
  restoreRunnerCheckpoint,
  restSecondsFor,
  serializeRunner,
  startRunner,
  type LegacyRunnerSlot,
  type RunnerCheckpoint,
  type RunnerEvent,
  type RunnerHaltReason,
  type RunnerPhase,
  type RunnerSlot,
  type RunnerSlotInput,
  type RunnerStartConfig,
  type RunnerStartOptions,
  type RunnerState,
  type RunnerTarget,
  type RunnerWork,
} from './sessionRunner';
export {
  SESSION_OUTCOME_ENGINE_VERSION,
  SessionOutcomeValidationError,
  evaluateSessionOutcome,
  type SessionOutcomeDecision,
  type SessionOutcomeEvidence,
  type SessionOutcomeInput,
  type SessionOutcomeKind,
  type SessionOutcomeOriginKind,
  type SessionOutcomeProvenanceKind,
  type SessionOutcomeSetInput,
  type SessionOutcomeSlotInput,
  type SessionOutcomeTerminal,
} from './sessionOutcome';
export {
  projectChainsFromGraph,
  type MovementFamilyInput,
  type CapabilityEdgeInput,
  type ProjectedChainRow,
} from './chainProjection';
export {
  evaluateReturn,
  LAYOFF_GAP_DAYS,
  RETURN_OPTIONS,
  type ReturnAction,
  type ReturnEvaluation,
} from './returnFromLayoff';
export {
  mapImplementToTier,
  sortPickerMovements,
  groupAndSortPickerMovements,
  PICKER_TIER_NAMES,
  TIER_3_CAPTION,
  type PickerTier,
  type PickerSortableMovement,
} from './pickerTiering';
