export {
  AdjustmentValidationError,
  clampAdjustment,
  CUE_MAX_CHARS,
  CUE_MIN_CHARS,
  CUE_RE,
  LOAD_MODIFIER_LITERALS,
  NEUTRAL_ADJUSTMENT,
  RPE_CAP_LITERALS,
  SET_MODIFIER_FLOOR,
  SET_MODIFIER_LITERALS,
  validateAdjustment,
  type AdjustmentVector,
} from './outputSchema';
export {
  DEFAULT_PROFILE,
  DIFFICULTY_RANK,
  DIFFICULTY_RATINGS,
  ENERGY_SYSTEMS,
  EQUIPMENT_ITEMS,
  EQUIPMENT_PRESETS,
  EXPERIENCE_SEVERITY,
  MOVEMENT_PATTERNS,
  MOVEMENT_PREFERENCE,
  MOVEMENT_PREFIXES,
  OBJECTIVES,
  BIG4_LIFTS,
  MACRO_PHASES,
  PATTERN_TO_CATEGORY,
  PREFIX_TO_IMPLEMENT,
  PROGRESSION_METHODS,
  SCHEMA_TYPES,
  TAXONOMY_CATEGORIES,
  TAXONOMY_IMPLEMENTS,
  TRAINING_AGES,
  type BodyNote,
  type DifficultyRating,
  type EnergySystem,
  type EquipmentItem,
  type MovementPattern,
  type MovementPrefix,
  type MovementPrefixCondition,
  type MovementPreference,
  type Objective,
  type MacroPhase,
  type ProgressionMethod,
  type SchemaType,
  type StateVectorRow,
  type TaxonomyCategory,
  type TaxonomyImplement,
  type TrainingAge,
  type UserProfile,
} from './types';
export { evaluatePolicy } from './policyReference';
export {
  derivePrescription,
  type DeriveInput,
  type DerivedPrescription,
  type ReportInput,
} from './derivePrescription';
export {
  addDaysIso,
  availableMovements,
  BLOCK_WEEKS,
  generateBlock,
  HYBRID_TAX_THRESHOLD,
  MACRO_BLOCKS,
  MACRO_TOTAL_WEEKS,
  macroPhaseOf,
  OVERREACH_ACWR,
  SCHEMA_FATIGUE_COST,
  targetLoadKg,
  targetPct,
  type BlockFocus,
  type BlockInput,
  type BlockPhase,
  type BlockPlan,
  type GeneratorMovement,
  type PlannedSessionPlan,
  type PlannedSlotPlan,
} from './blockGenerator';
export {
  calculateEffectiveLoad,
  NEUTRAL_PREFIX_MODIFIER,
  type EffectiveLoad,
} from './conditionEngine';
export {
  applyProfileLimits,
  applySeverityToGuardrail,
  EXPERIENCE_TRIAGE,
  scaleGuardrailForExperience,
  type ProfileContext,
  type ProfileLimitedPrescription,
} from './profileLimits';
export {
  computeSubstitutions,
  DEFAULT_ACCESSORY_RATIO,
  JOINTS,
  NIGGLE_MAX,
  NIGGLE_MIN,
  PATTERN_JOINTS,
  SUBSTITUTION_COLORS,
  type DaySwapOption,
  type FutureSlot,
  type Joint,
  type NiggleInput,
  type RegressionOption,
  type SubstitutionInput,
  type SubstitutionLayer,
  type SubstitutionMovement,
  type SubstitutionResult,
  type TriageCluster,
  type TriageClusterMember,
} from './substitution';
export {
  RED_FLAG_PAIN,
  RED_FLAG_SYSTEMIC,
  resolveReport,
  scanRedFlags,
  type RedFlagScan,
  type ResolvedReport,
} from './semantic/redFlag';
export { getPrescription, type AdjustmentSource, type Prescription } from './prescribe';
export { normalize, packVectors, topK, type Match } from './semantic/cosine';
export {
  flattenTexts,
  isNoOpGuardrail,
  loadCodebase,
  type Guardrail,
  type LoadedCodebase,
  type PhraseCodebase,
  type PhraseEntry,
} from './semantic/codebase';
export { type Embedder } from './semantic/embedder';
export { WordPieceTokenizer, type TokenizerSpec } from './semantic/wordpiece';
export {
  createMiniLmEmbedder,
  type MiniLmEmbedderOptions,
  type OrtSessionLike,
  type OrtTensorCtor,
} from './semantic/onnxEmbedder';
export {
  AMBIGUITY_MARGIN,
  CONFIDENCE_THRESHOLD,
  applyGuardrail,
  moreConservative,
  triage,
  type SessionDirective,
  type TriageResult,
} from './semantic/triage';
