/**
 * WO-09 R2 Part C: the static family loader table.
 *
 * GENERATED by tools/rendering/wo09_split_preview_manifest.mjs - do not edit
 * by hand. Metro needs one literal `require` per family file; the index
 * (previewIndex.json) maps a movement id to the key used here, and manifest.ts
 * calls a loader the first time one of a family's movements is shown, then
 * caches the parsed family.
 */

export interface PreviewFamilyFile {
  readonly family: string;
  readonly entries: readonly unknown[];
}

export const FAMILY_LOADERS: Readonly<Record<string, () => PreviewFamilyFile>> = {
  'back-extension__prone': () => require('./families/back-extension__prone.json') as PreviewFamilyFile,
  'calf-raise__seated': () => require('./families/calf-raise__seated.json') as PreviewFamilyFile,
  'calf-raise__standing': () => require('./families/calf-raise__standing.json') as PreviewFamilyFile,
  'carry__standing': () => require('./families/carry__standing.json') as PreviewFamilyFile,
  'dead-bug__supine': () => require('./families/dead-bug__supine.json') as PreviewFamilyFile,
  'dip__seated-supported': () => require('./families/dip__seated-supported.json') as PreviewFamilyFile,
  'elbow-extension__bodyweight-supported': () => require('./families/elbow-extension__bodyweight-supported.json') as PreviewFamilyFile,
  'elbow-extension__decline': () => require('./families/elbow-extension__decline.json') as PreviewFamilyFile,
  'elbow-extension__incline': () => require('./families/elbow-extension__incline.json') as PreviewFamilyFile,
  'elbow-extension__standing-overhead': () => require('./families/elbow-extension__standing-overhead.json') as PreviewFamilyFile,
  'elbow-extension__standing-pushdown': () => require('./families/elbow-extension__standing-pushdown.json') as PreviewFamilyFile,
  'elbow-extension__supine': () => require('./families/elbow-extension__supine.json') as PreviewFamilyFile,
  'elbow-flexion__incline': () => require('./families/elbow-flexion__incline.json') as PreviewFamilyFile,
  'elbow-flexion__preacher': () => require('./families/elbow-flexion__preacher.json') as PreviewFamilyFile,
  'elbow-flexion__prone-supported': () => require('./families/elbow-flexion__prone-supported.json') as PreviewFamilyFile,
  'elbow-flexion__seated': () => require('./families/elbow-flexion__seated.json') as PreviewFamilyFile,
  'elbow-flexion__standing': () => require('./families/elbow-flexion__standing.json') as PreviewFamilyFile,
  'face-pull__standing': () => require('./families/face-pull__standing.json') as PreviewFamilyFile,
  'flye__decline': () => require('./families/flye__decline.json') as PreviewFamilyFile,
  'flye__incline': () => require('./families/flye__incline.json') as PreviewFamilyFile,
  'flye__supine': () => require('./families/flye__supine.json') as PreviewFamilyFile,
  'front-raise__incline': () => require('./families/front-raise__incline.json') as PreviewFamilyFile,
  'front-raise__standing': () => require('./families/front-raise__standing.json') as PreviewFamilyFile,
  'glute-kickback__standing': () => require('./families/glute-kickback__standing.json') as PreviewFamilyFile,
  'hip-extension__standing': () => require('./families/hip-extension__standing.json') as PreviewFamilyFile,
  'hip-extension__supine': () => require('./families/hip-extension__supine.json') as PreviewFamilyFile,
  'hip-hinge__standing': () => require('./families/hip-hinge__standing.json') as PreviewFamilyFile,
  'horizontal-press__incline': () => require('./families/horizontal-press__incline.json') as PreviewFamilyFile,
  'horizontal-press__supine': () => require('./families/horizontal-press__supine.json') as PreviewFamilyFile,
  'horizontal-pull__bent-over': () => require('./families/horizontal-pull__bent-over.json') as PreviewFamilyFile,
  'horizontal-pull__kneeling': () => require('./families/horizontal-pull__kneeling.json') as PreviewFamilyFile,
  'horizontal-pull__prone-supported': () => require('./families/horizontal-pull__prone-supported.json') as PreviewFamilyFile,
  'horizontal-pull__seated': () => require('./families/horizontal-pull__seated.json') as PreviewFamilyFile,
  'horizontal-pull__standing': () => require('./families/horizontal-pull__standing.json') as PreviewFamilyFile,
  'horizontal-pull__supine': () => require('./families/horizontal-pull__supine.json') as PreviewFamilyFile,
  'isolation-other__incline': () => require('./families/isolation-other__incline.json') as PreviewFamilyFile,
  'lateral-raise__seated': () => require('./families/lateral-raise__seated.json') as PreviewFamilyFile,
  'lateral-raise__standing': () => require('./families/lateral-raise__standing.json') as PreviewFamilyFile,
  'locomotion__standing': () => require('./families/locomotion__standing.json') as PreviewFamilyFile,
  'lunge__reverse': () => require('./families/lunge__reverse.json') as PreviewFamilyFile,
  'lunge__split-stance': () => require('./families/lunge__split-stance.json') as PreviewFamilyFile,
  'lunge__standing': () => require('./families/lunge__standing.json') as PreviewFamilyFile,
  'lunge__traveling': () => require('./families/lunge__traveling.json') as PreviewFamilyFile,
  'pallof__standing': () => require('./families/pallof__standing.json') as PreviewFamilyFile,
  'plank__prone': () => require('./families/plank__prone.json') as PreviewFamilyFile,
  'push-up__decline': () => require('./families/push-up__decline.json') as PreviewFamilyFile,
  'push-up__floor': () => require('./families/push-up__floor.json') as PreviewFamilyFile,
  'push-up__incline': () => require('./families/push-up__incline.json') as PreviewFamilyFile,
  'rear-delt__bent-over': () => require('./families/rear-delt__bent-over.json') as PreviewFamilyFile,
  'rear-delt__standing': () => require('./families/rear-delt__standing.json') as PreviewFamilyFile,
  'shoulder-raise__standing': () => require('./families/shoulder-raise__standing.json') as PreviewFamilyFile,
  'shoulder-rotation__standing': () => require('./families/shoulder-rotation__standing.json') as PreviewFamilyFile,
  'shrug__standing': () => require('./families/shrug__standing.json') as PreviewFamilyFile,
  'squat__standing': () => require('./families/squat__standing.json') as PreviewFamilyFile,
  'squat__sumo-stance': () => require('./families/squat__sumo-stance.json') as PreviewFamilyFile,
  'straight-arm-pulldown__standing': () => require('./families/straight-arm-pulldown__standing.json') as PreviewFamilyFile,
  'trunk-flex__decline': () => require('./families/trunk-flex__decline.json') as PreviewFamilyFile,
  'trunk-flex__kneeling': () => require('./families/trunk-flex__kneeling.json') as PreviewFamilyFile,
  'trunk-flex__seated': () => require('./families/trunk-flex__seated.json') as PreviewFamilyFile,
  'trunk-flex__standing': () => require('./families/trunk-flex__standing.json') as PreviewFamilyFile,
  'trunk-flex__supine': () => require('./families/trunk-flex__supine.json') as PreviewFamilyFile,
  'trunk-side-bend__standing': () => require('./families/trunk-side-bend__standing.json') as PreviewFamilyFile,
  'trunk-twist__decline': () => require('./families/trunk-twist__decline.json') as PreviewFamilyFile,
  'trunk-twist__seated': () => require('./families/trunk-twist__seated.json') as PreviewFamilyFile,
  'trunk-twist__supine': () => require('./families/trunk-twist__supine.json') as PreviewFamilyFile,
  'vertical-press__seated': () => require('./families/vertical-press__seated.json') as PreviewFamilyFile,
  'vertical-press__standing': () => require('./families/vertical-press__standing.json') as PreviewFamilyFile,
  'vertical-pull__standing': () => require('./families/vertical-pull__standing.json') as PreviewFamilyFile,
  'wrist-flexion__seated': () => require('./families/wrist-flexion__seated.json') as PreviewFamilyFile,
  'wrist-flexion__standing': () => require('./families/wrist-flexion__standing.json') as PreviewFamilyFile,
};
