/**
 * manifest.ts — typed access to the offline movement-preview coverage manifest
 * (WO-09A bounded prototype).
 *
 * LOADING (R2 Part C): the data is an index (`previewIndex.json` — the shared
 * rig, box, character and frame interval, plus movement id -> family) and one
 * compact file per motion family (`families/<family>.json`, generated by
 * tools/rendering/wo09_split_preview_manifest.mjs). A family is validated and
 * cached the first time one of its movements is shown, so a screen that shows
 * one movement parses one family, never all of the entries.
 *
 * IDENTITY (the reason this file exists): a preview is bound to a movement by
 * its CANONICAL DATABASE IDENTITY, never by display name. Two independent keys
 * must agree before a drawing is shown:
 *
 *   1. `movement.movement_id` — the primary key every session, slot and
 *      progression row already references.
 *   2. `movement.media.assetKey` — movement_media.asset_key (migration 036),
 *      the repository's stable, unique, rename-proof media identity.
 *
 * If a future migration ever re-points an id at a different movement, or moves
 * an asset key, the two keys stop agreeing and the movement falls back to the
 * existing text + video UI. A wrong drawing on the wrong movement is the one
 * failure this prototype must never produce, so it fails closed.
 *
 * Renaming a movement changes NOTHING here: display names are recorded in the
 * manifest for review, and are never used to select a preview.
 */
import rawIndex from './previewIndex.json';
// Metro needs one literal `require` per family file, so the loader table is
// generated (see the header of familyLoaders.ts); previewIndex.json maps a
// movement id to the family key used here.
import { FAMILY_LOADERS, type PreviewFamilyFile } from './familyLoaders';
import type {
  BodyParameters,
  CanonicalPose,
  ViewName,
} from './canonicalFigure';
// The `derivesFrom` contract (R2 Part A) is a pure, import-free module so the
// offline evidence tools compile and run the SAME rules (the sharing pattern
// canonicalFigure.ts already uses). Resolution is applied here, at load.
import {
  BODY_TURN_MAX_DEG,
  IMPLEMENT_COUNTS,
  IMPLEMENT_ORIENTATIONS,
  IMPLEMENT_SCALE_MAX,
  IMPLEMENT_SCALE_MIN,
  deriveVariantEntry,
  isVariantEntry,
  readGripDeltaShape,
  readJointOffsetsShape,
  validateVariantSet,
  type FrameRole,
  type ImplementCount,
  type ImplementOrientation,
  type JointOffsets,
  type RawVariantLike,
} from './derivation';

export {
  BODY_TURN_MAX_DEG,
  IMPLEMENT_COUNTS,
  IMPLEMENT_ORIENTATIONS,
  IMPLEMENT_SCALE_MAX,
  IMPLEMENT_SCALE_MIN,
  INHERITABLE_FIELDS,
  GRIP_ELBOW_STEP_MAX_FACTOR,
  JOINT_OFFSET_MAX_SEGMENT_CHANGE,
  OFFSET_JOINTS,
  PEAK_STEP,
  REQUIRED_VARIANT_FIELDS,
  STEP_FAMILY_BY_BASE,
  STEP_LISTS,
  deriveVariantEntry,
  isVariantEntry,
  stepListForBase,
  validateVariantSet,
  verifyResolvedVariant,
} from './derivation';
export type { FrameRole, ImplementOrientation, JointOffsets, StepList } from './derivation';

export type { CanonicalPose, ViewName };

export type PreviewJointName =
  | 'ankle' | 'knee' | 'hip' | 'shoulder' | 'elbow' | 'hand' | 'head' | 'toe' | 'heel';

/** Canonical 11-joint topology + implement anchor b (locked shared rig). */
export type CanonicalJointName =
  | 'hd' // head center
  | 'nk' // neck / cervical pivot
  | 'hp' // hip / acetabulofemoral pivot
  | 'el' // near elbow
  | 'wr' // near wrist
  | 'ef' // far elbow
  | 'wf' // far wrist
  | 'kn' // near knee
  | 'an' // near ankle
  | 'kf' // far knee
  | 'af' // far ankle
  | 'b';  // implement / grip anchor

export type PreviewPoint = readonly [number, number];

export interface CanonicalJoints {
  hd: PreviewPoint;
  nk: PreviewPoint;
  hp: PreviewPoint;
  el: PreviewPoint;
  wr: PreviewPoint;
  ef: PreviewPoint;
  wf: PreviewPoint;
  kn: PreviewPoint;
  an: PreviewPoint;
  kf: PreviewPoint;
  af: PreviewPoint;
  b?: PreviewPoint;
}

export type LegacyBodyType = 'male' | 'female';
export type BodyType = 'neutral' | LegacyBodyType;

// The body-parameter contract lives with the layout it parameterizes;
// manifest.ts re-exports it so existing import sites keep working. The
// production manifest's historical dualBody metadata remains legacy-only.
export { CANONICAL_BODY_PARAMETERS, DUAL_BODY_PARAMETERS } from './canonicalFigure';
export type { BodyParameters } from './canonicalFigure';

/** Strict chalk accent color and usage policy rules. */
export const CHALK_VISUAL_RULES = {
  accentColor: '#EFC94C',
  policy: 'position-only' as const,
  allowedTargets: ['scrubber', 'progress-track', 'active-position-tick'] as const,
  forbiddenTargets: ['limbs', 'joints', 'bones', 'head', 'torso', 'arrows'] as const,
} as const;

export interface PreviewFrame {
  /** Stable frame id, unique within its movement. */
  id: string;
  /** One line of plain coaching language describing the drawn position. */
  caption: string;
  joints: Readonly<Record<PreviewJointName, PreviewPoint>>;
}

/** One keyframe of the canonical 11-joint rig (+ optional implement anchor). */
export interface CanonicalFrame {
  id: string;
  caption: string;
  joints: CanonicalPose;
}

/** Which rig a covered entry's frames are drawn with. */
export type PreviewRig = 'legacy' | 'canonical';

export interface CoveredFrames {
  rig: 'legacy';
  frames: readonly PreviewFrame[];
}

export interface CoveredCanonicalFrames {
  rig: 'canonical';
  /** Camera projection for the canonical rig ('side' = sagittal, 'front' = coronal). */
  view: ViewName;
  /** Camera framing in manifest box units [x, y, w, h]. */
  viewBox: readonly [number, number, number, number];
  /** Per-segment durations (ms) for eased interpolation between keyframes. */
  segmentDurationsMs?: readonly number[];
  frames: readonly CanonicalFrame[];
  /**
   * Curated reduced-motion sequence: indices into `frames`, 8–12 distinct
   * teaching positions. Playback always uses all `frames`; stills use this.
   */
  reducedMotionFrames?: readonly number[];
}

export type CoveredFrameData = CoveredFrames | CoveredCanonicalFrames;

export type PreviewStatus = 'covered' | 'pending' | 'intentionally_unsuitable';

interface PreviewEntryBase {
  movementId: number;
  assetKey: string;
  /** Recorded for review only — NEVER used to select a preview. */
  name: string;
  pattern: string;
}

export interface CoveredPreview extends PreviewEntryBase {
  status: 'covered';
  previewId: string;
  implement: 'dumbbells' | null;
  summary: string;
  frameData: CoveredFrameData;
  /**
   * The keyframe list regardless of rig (legacy stick frames or canonical
   * poses). Derived from `frameData`; every keyframe carries id/caption/joints.
   */
  frames: CoveredFrameData['frames'];
  /**
   * Variant-only: the step of every base frame id, drawn from the base's
   * movement FAMILY list (STEP_LISTS — curl, row, squat, carry, pulldown,
   * hinge), so the vocabulary is per family, not fixed. The implement tilt is
   * drawn ONLY on the frame whose step is `peak`; base entries carry no steps
   * at all, so their drawing path is unchanged.
   */
  frameRoles?: Readonly<Record<string, FrameRole>>;
  /** Variant-only: the implement orientation this variant asks for. */
  implementOrientation?: ImplementOrientation;
  /** Variant-only: how many implements this variant draws (1 = one bell). */
  implementCount?: ImplementCount;
  /** Owner batch (B1-20-R2): implement scale; omitted means 1. */
  implementScale?: number;
  /** Owner batch (B1-20-R2): front-view body turn in degrees; omitted means none. */
  bodyTurnDeg?: number;
  /** Variant-only (B1-55): constant per-joint draw-time offsets; omitted means none. */
  jointOffsets?: JointOffsets;
  /** Variant-only, front view (B1-300): grip change per hand; omitted means none. */
  gripDelta?: number;
}

export interface UncoveredPreview extends PreviewEntryBase {
  status: 'pending' | 'intentionally_unsuitable';
  reason: string;
  viewBox?: readonly [number, number, number, number];
  view?: ViewName;
  equipment?: string;
  coachingIntent?: string;
  instructions?: string;
  cues?: string;
  techniqueCitations?: readonly string[];
  /** Variant contract: implements drawn; omitted means the slug's default. */
  implementCount?: 1 | 2;
  /** Owner batch (B1-20-R2): implement scale; omitted means 1. */
  implementScale?: number;
  /** Owner batch (B1-20-R2): front-view body turn in degrees; omitted means none. */
  bodyTurnDeg?: number;
  /** Variant-only (B1-55): constant per-joint draw-time offsets; omitted means none. */
  jointOffsets?: JointOffsets;
  /** Variant-only, front view (B1-300): grip change per hand; omitted means none. */
  gripDelta?: number;
}

export type PreviewEntry = CoveredPreview | UncoveredPreview;

/** The minimum a caller must carry for a preview to be resolvable. */
export interface PreviewSubject {
  movement_id: number;
  name?: string;
  pattern?: string;
  media?: {
    assetKey?: string | null;
    asset_key?: string | null;
    status?: string | null;
    revision?: number | null;
    fallbackUrl?: string | null;
  } | null;
}


interface RawJoints { [joint: string]: number[] }
interface RawFrame { id: string; caption: string; joints: RawJoints }
interface RawEntry {
  movementId: number;
  assetKey: string;
  name: string;
  pattern: string;
  status: string;
  previewId?: string;
  implement?: string | null;
  summary?: string;
  frames?: RawFrame[];
  segmentDurationsMs?: number[];
  reason?: string;
  viewBox?: number[];
  view?: string;
  equipment?: string;
  coachingIntent?: string;
  instructions?: string;
  cues?: string;
  techniqueCitations?: string[];
  /** Optional curated reduced-motion sequence: indices into `frames`. */
  reducedMotionFrames?: number[];
  /** Variant contract (R2 Part A): the base this entry derives from. */
  derivesFrom?: number;
  /** Variant contract: per-base-frame step role, keyed by base frame id. */
  frameRoles?: Record<string, string>;
  /** Variant contract: per-base-frame caption text, keyed by base frame id. */
  captionOverrides?: Record<string, string>;
  /** Variant contract: 'flat' (default) or 'supinated'. */
  implementOrientation?: string;
  /** Variant contract: implements drawn; omitted means the slug's default. */
  implementCount?: number;
  /** Owner batch (B1-20-R2): implement scale; omitted means 1. */
  implementScale?: number;
  /** Owner batch (B1-20-R2): front-view body turn in degrees; omitted means none. */
  bodyTurnDeg?: number;
  /** Variant contract (B1-55): constant per-joint draw-time offsets. */
  jointOffsets?: Record<string, number[]>;
  /** Variant contract (B1-300): grip change per hand, front view only. */
  gripDelta?: number;
  /** Variant contract: declares inherited techniqueCitations as inherited. */
  techniqueCitationsInherited?: boolean;
}

const JOINT_NAMES: readonly PreviewJointName[] = [
  'ankle', 'knee', 'hip', 'shoulder', 'elbow', 'hand', 'head', 'toe', 'heel',
];

// One cast at the boundary: TypeScript types a JSON import structurally, and
// the two entry shapes (covered / uncovered) are a union it cannot narrow by
// itself. The shared blocks below are read at module load; a family's entries
// are validated the first time that family loads (loadPreviewFamily), so a
// malformed file is a loud failure rather than a wrong drawing.
const raw = rawIndex as unknown as {
  schemaVersion: number;
  box: { width: number; height: number; ground: number };
  character: { bones: Record<string, number>; headRadius: number; bonePairs: string[][] };
  frameIntervalMs: number;
  techniqueReview: { status: string; detail: string };
  sharedRig?: {
    version: string;
    jointTopology: string[];
    dualBody: Record<LegacyBodyType, BodyParameters>;
    chalkRules: { color: string; policy: string; prohibitedElements: string[] };
  };
  families: Record<string, { key: string; movements: number[] }>;
  movementFamily: Record<string, string>;
  movementOrder: number[];
};
if (raw.schemaVersion !== 2) {
  throw new Error(`movement preview: unsupported preview index schema ${raw.schemaVersion}`);
}

function readFrame(entry: RawEntry, frame: RawFrame): PreviewFrame {
  const joints: Record<string, PreviewPoint> = {};
  for (const joint of JOINT_NAMES) {
    const point = frame.joints[joint];
    if (point === undefined || point.length !== 2
      || !Number.isFinite(point[0]) || !Number.isFinite(point[1])) {
      throw new Error(`movement preview ${entry.movementId}/${frame.id}: bad joint ${joint}`);
    }
    joints[joint] = [point[0], point[1]] as const;
  }
  return { id: frame.id, caption: frame.caption, joints: joints as Record<PreviewJointName, PreviewPoint> };
}

const CANONICAL_JOINT_NAMES: readonly Exclude<CanonicalJointName, 'b'>[] = [
  'hd', 'nk', 'hp', 'el', 'wr', 'ef', 'wf', 'kn', 'an', 'kf', 'af',
];

function readCanonicalFrame(entry: RawEntry, frame: RawFrame): CanonicalFrame {
  // Family 13: `bt` is the held bar's tilt and Entry 0184: `ct` is the chin-stop
  // flag. Both are finite scalars rather than joint points.
  const joints: Record<string, PreviewPoint | number> = {};
  for (const joint of CANONICAL_JOINT_NAMES) {
    const point = frame.joints[joint];
    if (point === undefined || point.length !== 2
      || !Number.isFinite(point[0]) || !Number.isFinite(point[1])) {
      throw new Error(`movement preview ${entry.movementId}/${frame.id}: bad canonical joint ${joint}`);
    }
    joints[joint] = [point[0], point[1]] as const;
  }
  const anchor = frame.joints.b;
  if (anchor !== undefined) {
    if (anchor.length !== 2 || !Number.isFinite(anchor[0]) || !Number.isFinite(anchor[1])) {
      throw new Error(`movement preview ${entry.movementId}/${frame.id}: bad canonical joint b`);
    }
    joints.b = [anchor[0], anchor[1]];
  }
  // Family 13: `bt` is the held bar's tilt, a finite scalar rather than a joint, so
  // it is carried through the same validated path. Dropping it here would draw the
  // app's motion frames with a level bar while the stills and the evidence show it
  // tilted at the top of the curl. Entry 0184's `ct`, the chin-stop flag, rides the
  // same path so the finish-line tick is on the app's own motion frames.
  for (const flag of ['bt', 'ct', 'se', 'ca', 'ra', 'pe', 'sa', 'fo', 'ke', 'rl', 'ir', 'tp', 'la'] as const) {
    const value = (frame.joints as Record<string, unknown>)[flag];
    if (value === undefined) continue;
    if (typeof value !== 'number' || !Number.isFinite(value)) {
      throw new Error(`movement preview ${entry.movementId}/${frame.id}: bad canonical ${flag}`);
    }
    joints[flag] = value;
  }
  return {
    id: frame.id,
    caption: frame.caption,
    joints: joints as unknown as CanonicalPose,
  };
}

/** The camera projection is mandatory for canonical entries and validated. */
function readView(entry: RawEntry): ViewName {
  if (entry.view !== 'side' && entry.view !== 'front' && entry.view !== 'oblique') {
    throw new Error(`movement preview ${entry.movementId}: canonical entry needs view 'side'|'front'|'oblique'`);
  }
  return entry.view;
}

function readViewBox(entry: RawEntry): readonly [number, number, number, number] {
  const vb = entry.viewBox;
  if (vb === undefined || vb.length !== 4 || vb.some((n) => !Number.isFinite(n))) {
    throw new Error(`movement preview ${entry.movementId}: canonical entry needs a 4-number viewBox`);
  }
  return [vb[0], vb[1], vb[2], vb[3]];
}

function readCoveredFrames(entry: RawEntry): CoveredFrameData {
  const frames = entry.frames ?? [];
  if (frames.length === 0) {
    throw new Error(`movement preview ${entry.movementId}: incomplete covered entry`);
  }
  const first = frames[0].joints ?? {};
  const isCanonical = first.nk !== undefined || first.hd !== undefined;
  if (isCanonical) {
    return {
      rig: 'canonical',
      view: readView(entry),
      viewBox: readViewBox(entry),
      segmentDurationsMs: entry.segmentDurationsMs,
      frames: frames.map((frame) => readCanonicalFrame(entry, frame)),
      ...(entry.reducedMotionFrames !== undefined
        ? { reducedMotionFrames: readReducedMotionFrames(entry, frames) }
        : {}),
    };
  }
  return { rig: 'legacy', frames: frames.map((frame) => readFrame(entry, frame)) };
}

/**
 * Curated reduced-motion teaching sequence: indices into `frames`, each in
 * range, unique, 8–12 positions (the audit's usability band), strictly
 * increasing so the scrubber order matches authored teaching order.
 */
function readReducedMotionFrames(entry: RawEntry, frames: RawFrame[]): readonly number[] {
  const indices = entry.reducedMotionFrames ?? [];
  const frameCount = frames.length;
  if (indices.length < 8 || indices.length > 12) {
    throw new Error(`movement preview ${entry.movementId}: reducedMotionFrames needs 8-12 entries`);
  }
  if (new Set(indices).size !== indices.length) {
    throw new Error(`movement preview ${entry.movementId}: reducedMotionFrames must be unique`);
  }
  for (const index of indices) {
    if (!Number.isInteger(index) || index < 0 || index >= frameCount) {
      throw new Error(`movement preview ${entry.movementId}: reducedMotionFrames index out of range`);
    }
  }
  for (let i = 1; i < indices.length; i++) {
    if (indices[i] <= indices[i - 1]) {
      throw new Error(`movement preview ${entry.movementId}: reducedMotionFrames must strictly increase`);
    }
  }
  return indices;
}

/**
 * Variant frame roles (R2 Part A). Every frame of the resolved entry carries
 * exactly one step role, keyed by the frame's own id — never by position. A
 * base entry has no roles at all, so this path is not entered for it.
 */
function readFrameRoles(
  entry: RawEntry,
  frames: readonly { id: string }[],
): Readonly<Record<string, FrameRole>> {
  // Only a derived variant carries steps. A record with roles but no base
  // pointer is hand-authored data the resolver never checked, and drawing it
  // would silently ignore the roles (critic finding A2-C2), so it is refused
  // here rather than read as flat.
  if (entry.derivesFrom === undefined) {
    throw new Error(`movement preview ${entry.movementId}: frameRoles on an entry that carries no derivesFrom`);
  }
  const roles = entry.frameRoles ?? {};
  const out: Record<string, FrameRole> = {};
  for (const frame of frames) {
    const role = roles[frame.id];
    if (role === undefined) {
      throw new Error(`movement preview ${entry.movementId}: no frame role for frame ${frame.id}`);
    }
    if (typeof role !== 'string' || role.trim().length === 0) {
      throw new Error(`movement preview ${entry.movementId}: frame ${frame.id} has an empty role`);
    }
    out[frame.id] = role;
  }
  for (const key of Object.keys(roles)) {
    if (!frames.some((frame) => frame.id === key)) {
      throw new Error(`movement preview ${entry.movementId}: frame role keyed to unknown frame ${key}`);
    }
  }
  return out;
}

/** Variant implement orientation; anything but flat|supinated fails loudly. */
function readImplementOrientation(entry: RawEntry): ImplementOrientation {
  const value = entry.implementOrientation;
  if (value === undefined || !(IMPLEMENT_ORIENTATIONS as readonly string[]).includes(value)) {
    throw new Error(`movement preview ${entry.movementId}: implementOrientation must be ${IMPLEMENT_ORIENTATIONS.join('|')}`);
  }
  return value as ImplementOrientation;
}

/** Variant implement count; anything but 1|2 fails loudly. */
function readImplementCount(entry: RawEntry): 1 | 2 {
  const value = entry.implementCount;
  if (value === undefined || !(IMPLEMENT_COUNTS as readonly number[]).includes(value)) {
    throw new Error(`movement preview ${entry.movementId}: implementCount must be ${IMPLEMENT_COUNTS.join('|')}`);
  }
  return value as 1 | 2;
}

/** Implement scale; a number in range, and only on a movement holding one. */
function readImplementScale(entry: RawEntry): number {
  const value = entry.implementScale;
  if (value === undefined
    || !(value >= IMPLEMENT_SCALE_MIN && value <= IMPLEMENT_SCALE_MAX)) {
    throw new Error(`movement preview ${entry.movementId}: implementScale must be between ${IMPLEMENT_SCALE_MIN} and ${IMPLEMENT_SCALE_MAX}`);
  }
  if (entry.equipment === undefined || entry.equipment === 'none') {
    throw new Error(`movement preview ${entry.movementId}: implementScale requires a held implement; ${JSON.stringify(entry.equipment)} is not one`);
  }
  return value;
}

/** Front-view body turn in degrees; refused on anything not drawn front-on. */
function readBodyTurnDeg(entry: RawEntry): number {
  const value = entry.bodyTurnDeg;
  if (value === undefined || !(value > 0 && value <= BODY_TURN_MAX_DEG)) {
    throw new Error(`movement preview ${entry.movementId}: bodyTurnDeg must be above 0 and at most ${BODY_TURN_MAX_DEG}`);
  }
  if (entry.view !== 'front') {
    throw new Error(`movement preview ${entry.movementId}: bodyTurnDeg is a front-view override; this movement is drawn ${JSON.stringify(entry.view)}`);
  }
  return value;
}

/**
 * Variant joint offsets (B1-55). Variant-only: a record carrying offsets but no
 * base pointer is data the resolver never measured against a base frame, so it
 * is refused here rather than drawn. The shape rule is the contract's own.
 */
function readJointOffsets(entry: RawEntry): JointOffsets {
  const where = `movement preview ${entry.movementId}`;
  if (entry.derivesFrom === undefined) {
    throw new Error(`${where}: jointOffsets on an entry that carries no derivesFrom; offsets are variant-only`);
  }
  return readJointOffsetsShape(where, entry.jointOffsets);
}

/**
 * Variant grip change (B1-300). Variant-only: a record carrying it without a
 * base pointer was never measured against a base frame, so it is refused here
 * rather than drawn. A record WITH a base pointer reaches this reader only
 * through deriveVariantEntry, whose checkGripDelta has already refused a side
 * view, an unreachable grip and a jumping elbow. The shape rule is the
 * contract's own.
 */
function readGripDelta(entry: RawEntry): number {
  const where = `movement preview ${entry.movementId}`;
  if (entry.derivesFrom === undefined) {
    throw new Error(`${where}: gripDelta on an entry that carries no derivesFrom; a grip change is variant-only`);
  }
  return readGripDeltaShape(where, entry.gripDelta);
}

function readEntry(entry: RawEntry): PreviewEntry {
  if (entry.status === 'covered') {
    if (entry.previewId === undefined || entry.summary === undefined
      || entry.frames === undefined || entry.frames.length === 0) {
      throw new Error(`movement preview ${entry.movementId}: incomplete covered entry`);
    }
    const covered: CoveredPreview = {
      movementId: entry.movementId,
      assetKey: entry.assetKey,
      name: entry.name,
      pattern: entry.pattern,
      status: 'covered',
      previewId: entry.previewId,
      implement: entry.implement === 'dumbbells' ? 'dumbbells' : null,
      summary: entry.summary,
      frameData: readCoveredFrames(entry),
      frames: [],
    };
    covered.frames = covered.frameData.frames;
    if (entry.frameRoles !== undefined) {
      covered.frameRoles = readFrameRoles(entry, covered.frameData.frames);
    }
    if (entry.implementOrientation !== undefined) {
      covered.implementOrientation = readImplementOrientation(entry);
    }
    if (entry.implementCount !== undefined) {
      covered.implementCount = readImplementCount(entry);
    }
    if (entry.implementScale !== undefined) {
      covered.implementScale = readImplementScale(entry);
    }
    if (entry.bodyTurnDeg !== undefined) {
      covered.bodyTurnDeg = readBodyTurnDeg(entry);
    }
    if (entry.jointOffsets !== undefined) {
      covered.jointOffsets = readJointOffsets(entry);
    }
    if (entry.gripDelta !== undefined) {
      covered.gripDelta = readGripDelta(entry);
    }
    return covered;
  }
  if (entry.status !== 'pending' && entry.status !== 'intentionally_unsuitable') {
    throw new Error(`movement preview ${entry.movementId}: unknown status ${entry.status}`);
  }
  if (entry.reason === undefined || entry.reason.trim().length === 0) {
    throw new Error(`movement preview ${entry.movementId}: ${entry.status} needs a reason`);
  }
  return {
    movementId: entry.movementId,
    assetKey: entry.assetKey,
    name: entry.name,
    pattern: entry.pattern,
    status: entry.status,
    reason: entry.reason,
    viewBox: entry.viewBox as readonly [number, number, number, number] | undefined,
    view: entry.view as ViewName | undefined,
    equipment: entry.equipment,
    coachingIntent: entry.coachingIntent,
    instructions: entry.instructions,
    cues: entry.cues,
    techniqueCitations: entry.techniqueCitations,
    // B1-20-C2: a BASE entry may legitimately carry these drawing overrides
    // (owner ruling 2026-09-24: base 19's own bells are bigger and 20 inherits
    // them), so they are VALIDATED here rather than copied through a cast. A
    // scale on a movement that holds no implement, or a turn on a movement
    // drawn side-on, fails loudly instead of loading as a silent no-op that
    // the drawing would never honour.
    implementCount: entry.implementCount === undefined ? undefined : readImplementCount(entry),
    implementScale: entry.implementScale === undefined ? undefined : readImplementScale(entry),
    bodyTurnDeg: entry.bodyTurnDeg === undefined ? undefined : readBodyTurnDeg(entry),
    jointOffsets: entry.jointOffsets === undefined ? undefined : readJointOffsets(entry),
    gripDelta: entry.gripDelta === undefined ? undefined : readGripDelta(entry),
  };
}

export const PREVIEW_BOX = raw.box;
export const PREVIEW_CHARACTER = raw.character;
export const PREVIEW_FRAME_INTERVAL_MS = raw.frameIntervalMs;
export const PREVIEW_TECHNIQUE_REVIEW = raw.techniqueReview;
export const PREVIEW_SHARED_RIG = raw.sharedRig;

// Part C loads ONE family at a time: the index says which family a movement
// belongs to, then the family's own file is required the first time one of its
// movements is shown, validated, and cached — so a screen that shows one
// movement never parses the other families.
//
// A family file is self-contained (its base and that base's variants share the
// family, which the split generator enforces), so `validateVariantSet` runs per
// file. It still throws on a duplicate previewId, an unknown `derivesFrom`, a
// derivation chain or a required field that is missing or equals the base's
// value — a malformed family is a loud failure the first time it loads, never a
// wrong drawing.
// One boundary cast: the derivation module works on plain records (it must run
// in the offline tools too) and validates the shape itself, so the typed
// RawEntry literals above are passed through here rather than re-declared.
export interface LoadedFamily {
  readonly entries: readonly PreviewEntry[];
  readonly rawEntries: readonly RawEntry[];
  readonly covered: ReadonlyMap<number, CoveredPreview>;
}

const LOADED_FAMILIES = new Map<string, LoadedFamily>();

/**
 * Load, validate and cache ONE family. Exported for gate tests: the app's own
 * path is `resolveMovementPreview`, which calls this for the shown movement's
 * family only.
 */
export function loadPreviewFamily(slug: string): LoadedFamily {
  const cached = LOADED_FAMILIES.get(slug);
  if (cached !== undefined) return cached;
  const loader = FAMILY_LOADERS[slug];
  if (loader === undefined) throw new Error(`movement preview: no loader for family '${slug}'`);
  const file = loader() as unknown as Omit<PreviewFamilyFile, 'entries'> & { entries: RawEntry[] };
  const rawEntryRecords = file.entries as unknown as RawVariantLike[];
  validateVariantSet(rawEntryRecords);
  const derived = new Map<number, RawEntry>();
  for (const entry of file.entries) {
    if (!isVariantEntry(entry)) continue;
    const base = rawEntryRecords.find((candidate) => candidate.movementId === entry.derivesFrom);
    derived.set(
      entry.movementId,
      deriveVariantEntry(entry as unknown as RawVariantLike, base) as unknown as RawEntry,
    );
  }
  const entries = file.entries.map((entry) => readEntry(derived.get(entry.movementId) ?? entry));
  const covered = new Map<number, CoveredPreview>();
  for (const entry of entries) {
    if (entry.status !== 'covered') continue;
    if (covered.has(entry.movementId)) {
      throw new Error(`movement preview ${entry.movementId}: duplicate covered entry`);
    }
    covered.set(entry.movementId, entry);
  }
  const loaded: LoadedFamily = { entries, rawEntries: file.entries, covered };
  LOADED_FAMILIES.set(slug, loaded);
  return loaded;
}

/** The family file a movement lives in, or undefined when the preview holds no entry for it. */
function familySlugFor(movementId: number): string | undefined {
  return raw.movementFamily[String(movementId)];
}

/**
 * Every family's entries, in the manifest's own order — and the split is
 * checked against itself on the way through. A movement id carried by two
 * family files (a duplicate), an entry the index does not order, or an index id
 * no family carries (an orphan) throws here rather than drawing. The split
 * generator cannot produce any of the three, so this is the loud boundary for a
 * split that has been edited by hand.
 */
function collectEntries<T extends { movementId: number }>(
  ofFamily: (family: LoadedFamily) => readonly T[],
): T[] {
  const byMovementId = new Map<number, T>();
  for (const slug of new Set(Object.values(raw.movementFamily))) {
    for (const entry of ofFamily(loadPreviewFamily(slug))) {
      if (byMovementId.has(entry.movementId)) {
        throw new Error(`movement preview ${entry.movementId}: entry appears in two families`);
      }
      byMovementId.set(entry.movementId, entry);
    }
  }
  if (byMovementId.size !== raw.movementOrder.length) {
    throw new Error(
      `movement preview: the index orders ${raw.movementOrder.length} entries but the family files carry ${byMovementId.size}`,
    );
  }
  return raw.movementOrder.map((movementId) => {
    const entry = byMovementId.get(movementId);
    if (entry === undefined) {
      throw new Error(`movement preview ${movementId}: entry missing from its family`);
    }
    return entry;
  });
}

/**
 * Every resolved entry, in the manifest's own order, loading every family.
 * Tests and offline gates use this; the app's own path is
 * `resolveMovementPreview`, which loads one family. Touching this parses all of
 * the preview data, by design.
 */
export function previewEntries(): readonly PreviewEntry[] {
  return collectEntries((family) => family.entries);
}

/**
 * Every RAW entry (a variant's resolution not applied), in the manifest's own
 * order, loading every family. Exported for gate tests, like
 * `buildPreviewEntry`: the app's own path is `resolveMovementPreview`, which
 * loads one family.
 */
export function rawPreviewEntries(): readonly RawEntry[] {
  return collectEntries((family) => family.rawEntries);
}

/**
 * Manifest boundary, exported for gate tests: parse ONE raw manifest entry
 * with the same validation the module load applies. A covered entry whose
 * frames are canonical reads as rig 'canonical' (with view + viewBox); a
 * legacy entry reads as rig 'legacy'; anything malformed throws loudly.
 */
export function buildPreviewEntry(entry: unknown, base?: unknown): PreviewEntry {
  const rawEntry = entry as RawEntry;
  if (!isVariantEntry(rawEntry)) return readEntry(rawEntry);
  return readEntry(
    deriveVariantEntry(rawEntry as unknown as RawVariantLike, base as RawVariantLike | undefined) as unknown as RawEntry,
  );
}

/**
 * The covered preview for this movement, or null when the movement is unknown,
 * pending, unsuitable, unapproved, or its two identity keys disagree. Null
 * means "show the existing UI unchanged".
 *
 * FAIL-CLOSED APPROVAL BOUNDARY (WO-09 remediation A) — every one of these
 * gates must hold before a drawing is athlete-visible:
 *
 *   1. The qualified technique-review state is COMPLETE. While the manifest
 *      reports `pending`, NOTHING renders anywhere — not even the three
 *      legacy covered prototypes. Production callers use the manifest's own
 *      review state (the default); a caller may pass a review state only as an
 *      explicitly-labelled fixture in tests of the hypothetical approval path.
 *   2. The movement's own `movement_media.status` is `ready` under the
 *      existing data contract. An `external_fallback` or `planned` row means
 *      the drawing has not cleared the approval path and renders nothing.
 *   3. The manifest and DB identities agree (movement_id ↔ asset_key).
 */
export function resolveMovementPreview(
  subject: PreviewSubject | null | undefined,
  techniqueReview: { status: string } = PREVIEW_TECHNIQUE_REVIEW,
): CoveredPreview | null {
  if (!subject || typeof subject.movement_id !== 'number') return null;
  if (techniqueReview === null || techniqueReview.status !== 'complete') return null;
  const slug = familySlugFor(subject.movement_id);
  if (slug === undefined) return null;
  const entry = loadPreviewFamily(slug).covered.get(subject.movement_id);
  if (entry === undefined) return null;
  const mediaObj = subject.media as {
    assetKey?: string | null;
    asset_key?: string | null;
    status?: string | null;
  } | null | undefined;
  const assetKey = mediaObj?.assetKey ?? mediaObj?.asset_key;
  if (assetKey === undefined || assetKey === null) return null;
  if (assetKey !== entry.assetKey) return null;
  if (mediaObj?.status !== 'ready') return null;
  return entry;
}
